<table class="table">  

    <thead>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
        </tr>
        
    </thead>
    
    <tbody>
        
        <tr>
            <td><?= $this->user->fname; ?> <?= $this->user->lname; ?></td>
            <td><?= $this->user->phone; ?></td>
            <td><?= $this->user->email; ?></td>
        </tr>
        
    </tbody>
    
</table>
