<? $doNotShow = array('id');?>


<?if(isset($this->person) ):?>
<div class="well">
<a append:div="js-consumer-person-info"
   append:url="/consumer/async/person-info/id/"
   append:id="0" class=" pull-right js-append-info-to icon icon-remove"></a>

    <?foreach($this->person as $k=>$p):?>
        
        <?if(!in_array($k, $doNotShow)):?>
            <strong><?= ucwords(str_replace("_", " ", $k)) ?></strong> : <?=$this->escape($p)?><br />
        <?endif;?>
        
    <?endforeach;?>
</div>
<?endif;?>