<h4>Allergies, i.e., Medication, Food, Environment, etc.</h4>

    <div class="crud-create-update crud-load-template pointer hidden"
     id="allergy-bind-crud"
     data-id=''
     data-path='.:allergies'
     data-form='consumerallergiesform'
     data-title="Edit Allergies Data"
     data-params=''
     data-action='create'
     data-target='js-allergy-index'
     data-template='js-crud-edit-allergy'></div>
        
    <?= $this->TableHead( array("Allergy",
                                "Info",
                                "Edit",
                                "Delete" ), "table table-bordered", "js-allergy-index" ) ?>
	   
    <?if(isset($this->allergies)):?>
       <?foreach($this->allergies as $k=>$a):?>
        <?= $this->TableRow(array( $this->escape($a->allergy),
                                   $this->escape($a->info),
                                   "<center>
                                   <a class='crud-create-update icon icon-edit'
                                    data-action='update'
                                    data-bind='allergy-bind-crud'
                                    data-params='id:{$a->id},consumer_id:{$a->consumer_id}'></a></center>",
                                   "<center><a class='crud-delete icon icon-remove' data-bind='allergy-bind-crud' data-params='id:{$a->id}'></a></center>"
                                   ), "class='crud-row-{$a->id} highlight-child'"); ?>
       
       <?endforeach;?>
   <?endif;?>

    <?= $this->TableFoot("<tr><td colspan='4'><a class='crud-create-update pull-right'
                                                        data-action='create'
                                                        data-bind='allergy-bind-crud'
                                                        data-params='consumer_id:{$this->consumer_id}'>Add Allergy
                                                        </a></td></tr>" ) ?>
    

<script id="js-crud-edit-allergy" type="text/template">
    <% if( action == 'new' ){%>
        <tr class="crud-row-<%= helpers.escapeHtml(id) %> highlight-child">
    <%}%>
        <td><%= helpers.escapeHtml(values.allergy) %></td>
        <td><%= helpers.escapeHtml(values.info) %></td>
        <td>
            <center><a class='crud-create-update icon icon-edit'
                       data-action='update'
                       data-bind='allergy-bind-crud'
                       data-params='id:<%= helpers.escapeHtml(id) %>,consumer_id:<%= helpers.escapeHtml(id) %>'>
                       </a>
            </center>
        </td>		    
        <td>
        <center>
            <a class='crud-delete icon icon-remove'
               data-bind='allergy-bind-crud'
               data-params='id:<%= helpers.escapeHtml(id) %>'></a>
        </center>
        </td>
    <% if( action == 'new' ){%>
        </tr>
    <%}%>
</script>
