<h4>Exam information</h4>

<div class="crud-create-update crud-load-template pointer hidden"
    id="exam-bind-crud"
    data-id=''
    data-path='/exams'
    data-form='consumerexamform'
    data-title="Edit Hospital Exams"
    data-params='',
    data-action='create'
    data-target='js-exams-index'
    data-template='js-crud-edit-exam'
    data-callback='lightBox.dateFields'
	data-onCreate='DragData.addEvent'
    data-template-path='consumers/exams'></div>
<?
   $header = array( "Physician Name",
                    "Address",
                    "Phone",
                    "Exam Type",
                    "Date of Last Exam",
                    "Result of Exam",
                    "Edit",
                    "Delete"); ?>


   <div class="max-height-450px overflow-auto">
			<? if(isset( $this->physiciansExams )): ?>
			<?= $this->TableHead( $header , "table table-bordered js-exams-table data-table small-txt", "js-exams-table", "id='js-exams-index'" ) ?>
			<? ksort($this->physiciansExams) ?>
			<?foreach($this->physiciansExams as $p):?>
			<?foreach($p['exams'] as $e):?>
			<?$strDate = strtotime( $e->date ) ?>
			<?= $this->TableRow(array( $this->escape($this->Truncate($p["name"], 30)),
                                   $this->escape($this->Truncate($p["address"], 30)),
                                   $this->escape($p["phone"]),
                                   $this->escape($e->type),
                                   date('m/d/Y', $strDate ),
                                   "<div class='show-tooltip' title='".$this->escape($e->result)."' data-toggle='tooltip' >"
								   .$this->Truncate($this->escape($e->result), 30)."</div>",
                                   "<center><a class='crud-create-update icon icon-edit' 
                                                      data-params='id:{$e->id},cid:{$this->consumer_id}'
                                                      data-bind='exam-bind-crud' 
                                                      data-action='update'></a></center>",
                                                     
                                   "<center><a id='med-{$e->id}'
                                            class='crud-delete icon on-check icon-remove' 
                                                  data-bind='exam-bind-crud'
                                                  data-action='delete' 
                                                  data-params='id:{$e->id},cid:{$this->consumer_id}'></a></center>",
                                   ), "class='crud-row-{$e->id} highlight-child'"); ?>
    <?endforeach;?>
    <?endforeach;?> 
    <?= $this->TableFoot("<tr><td colspan='9'><a class='crud-create-update pull-right' 
                                                        data-params='cid:{$this->consumer_id}' 
                                                        data-action='create' 
                                                        data-bind='exam-bind-crud'>Add Exam</a></td></tr>") ?>
	<?endif;?>
	</div>



<script type="text/plain" id="js-crud-edit-exam">
	
	<%if(action == 'createExam') {%>
	 <tr class='crud-row-<%= helpers.escapeHtml(id) %> highlight-child'>
	<% } %>	
	
	
	<td><%= helpers.escapeHtml(physician.name.substring(0, 30))%></td>
	<td><%= helpers.escapeHtml(physician.address.substring(0, 30))%></td>
	<td><%= helpers.escapeHtml(physician.phone) %></td>
	<td><%= helpers.escapeHtml(values.type) %></td>
	<td><%= helpers.escapeHtml(values.date) %></td>
	<td><div title="<%=helpers.escapeHtml(values.result)%>"><%=helpers.escapeHtml(values.result.substring(0, 30))  %></div></td>

	<td>
    <center><a class='crud-create-update icon icon-edit' 
              data-params='id:<%= id %>,cid:<%= values.consumer_id %>'
              data-bind='exam-bind-crud' 
              data-action='update'></a></center>
    </td>
	
	<td>
	
	 <center><a class='crud-delete icon icon-remove' 
                data-bind='exam-bind-crud'
                data-action='delete' 
                data-params='id:<%= id %>,cid:<%= values.consumer_id %>'></a></center>
	</td>
	

	<%if(action == 'createExam') {%>
	 </tr>
	<% } %>

</script>

