<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLH9g4xG6aB3qiAHyyJXyJXsRGhv0wBnw&sensor=true&region=us"> </script>

<script type="text/plain" id="js-distance-template">
    
    <tr id="js-distance-row-<%=helpers.escapeHtml(id)%>" class="white-txt">
        <td>
            <small>
                <strong>
                    <span class='miles'><%=helpers.escapeHtml(distance)%></span> miles
                </strong>
                /
                <strong>
                <%=helpers.escapeHtml(time)%>
                </strong>
            </small>
        </td>
        <td title="<%=helpers.escapeHtml(point.a)%>">
            <strong>
                <small><%=helpers.escapeHtml(point.a).substring(0,25)%></small>
            </strong>        
        </td>
        <td title="<%=helpers.escapeHtml(point.b)%>">
        <strong>
            <small><%=helpers.escapeHtml(point.b).substring(0,25)%></small>
        </strong>
        </td>
        
        <td>
            <small>
                <strong>
                <acronym title="Reimbursement" >
                    Re: $<span class='reimburse'><%=helpers.escapeHtml(reimbursement)%></span>
                </acronym>
                <strong>
            </small>
        </td>
        
        
        <td><i class="pointer icon-remove js-remove-distance-row"></i></td>
            
    </tr>
</script>

<script type="text/plain" id="js-flash-template">
    
      <table id="flash-message" class="table table-stipped no-margin rounded-corners-bottom top-of-index pos-abs">
            <tbody>
                <%=html%>
                
            </tbody>

        </table> 
    
</script>



    <style type="text/css">
    .map-canvas{
        height: 700px;    
    }
    
    .map-canvas img{
        max-width: none;
    }
    
    .js-miles, .js-miles-bg {
        height: 52px;
        left: 90px;
        top: 5px;
        width: 34%;
    }
        
    .js-miles-bg {
        background-color: #555;          
        opacity:0.5;
        filter:alpha(opacity=50); 
    }
    
    
    .js-miles-distance{
        max-height: 450px;
        overflow: auto;
       
    }

    
    .js-address{
        
        font-size:80%;
        width:310px;
    }
    
    .js-small-toggle{       
        top:28px;
        right:5px;
        background:url('/img/trans50.png') 0 0;    
    }
    
    .js-small-move {
        top:5px;
        right:5px;
        background:url('/img/trans50.png') 0 0;    
    }
   
   #flash-message{
   background:url('/img/trans50.png') 0 0; 
    max-height: 450px;
    right: 129px;
    top: 62px;
    width: 100%;
   }
   
   #js-distance-total , #total-reimburse{ color:orange}
        
    </style>
 

<div class="row-fluid dark-bg">

<div class="span4">
        
        
        
<div id="info-canvas" class="info-canvas">

    <img src="/img/red-dot.png" class="js-click-to-update" field:action="start">
    <input type="text" id="info-canvas-start" class="btn js-address" field:action="start">
    <br />
    <img src="/img/blue-dot.png" class="js-click-to-update" field:action="end">
    <input type="text" id="info-canvas-end" class="btn js-address" field:action="end">

</div>
        

 <div id="js-miles-distance" class="js-miles-distance">
        
        <table class="table table-stipped no-margin">
            <tbody id="js-distance-table">
            </tbody>
            
            <tfoot class="no-margin">
                <tr>
                    <td colspan="5">
                        <small class="pull-right">
                            <strong>Totals:</strong>
                            <strong id="js-distance-total"></strong>
                            <span class="white-txt">~</span>
                            <strong id="total-reimburse">0.00</strong>
                        </small>
                    </td>
                    
                    
                </tr>
            </tfoot>

        </table>
        
    
        
    </div>

        
        
</div>

    <div class="span8 no-margin ">

    <div id="js-map-tools" class="pos-rel">
        
     <div class="js-miles-bg pos-abs second-of-index rounded-corners"> </div> 
     
     <div id="js-miles" class="js-miles rounded-corners pos-abs top-of-index pad-10px">
        
        <div class="btn-group">
            <a type="button" class="btn js-distance-calc">Distance</a>
            <a type="button" class="btn js-current-position">Current Location</a>
            <a type="button" class="btn js-center-center-pins">Center Pins</a>
        </div>

    
     
      
        <div class="pos-abs top-of-index rounded-corners-rt-bt js-small-toggle"
           data-action='up' title="Show mileage table">
            <i class="icon-chevron-up icon-white pointer" id="js-distance-toggle"> </i>
        </div>

        <div class="pos-abs top-of-index rounded-corners-rt-bt js-small-move"
           data-action='up' title="Move toolbar">
            <i class="icon-move icon-white pointer" id="js-distance-toggle"> </i>
        </div>
        
    </div>

     
     
  
    
    </div>


     
    <div id="map-canvas" class="map-canvas" > </div>
  
  </div>
  
  
    <script type="text/javascript">
 
        
      var CheckIn = {

            map:null,
            markers:{start:null, end:null},
            action:'start',
            coords: {lat:0, lng:0},
            infoWin:{start:null, end:null},
            
            init:function() {
            CheckIn.buildMap();
            /*
                        navigator.geolocation.getCurrentPosition(function(coords){
                            
                            console.log(position);
                            
                            
                            });
                        
                        return;
            
                    if (navigator.geolocation) {
                    
                    navigator.geolocation.getCurrentPosition(CheckIn.buildMap);
                    
                }else{
                    
                    alert("Geolocation is not supported by this browser.");
                }
                            
                */
                
            },
            
            noPosi:function(err){
                
                console.log(err);
            },
                           
            
            buildMap:function() {
                
                
               var latlng = new google.maps.LatLng(38.57549932907437,-121.50899308300018);
                    
               var options = {
                    center: latlng,
                    zoom: 10,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                    
                
                
                CheckIn.map = new google.maps.Map(document.getElementById("map-canvas"), options);
                CheckIn.appendStartMarker( latlng );
                
                $('body').delegate(".js-click-to-update", "click", CheckIn.update);
                $('body').delegate('.js-current-position', 'click', CheckIn.start);
                $('body').delegate('.js-distance-calc','click', CheckIn.distance);
                $('body').delegate('.js-remove-distance-row','click', CheckIn.removeDistance);
                $('body').delegate('.js-center-center-pins','click', CheckIn.centerMarkers);
                
                $("#js-distance-toggle").click(CheckIn.slideDistanceUp);
                $("#info-canvas-start").focus( function(){ $(this).select(); } );
                $("#info-canvas-end").focus( function(){ $(this).select(); } );
                
                
                CheckIn.destination();
                
                CheckIn.infoWin.start = new google.maps.InfoWindow({
                       content: "Find the <a class='js-distance-calc'>Distance</a> between the red marker and blue maker"
                });
              
                CheckIn.infoWin.end = new google.maps.InfoWindow({
                       content: "Drag me to your <a class='js-current-position'>current location</a>"
                });
              
            },
            
            
            
            
            appendStartMarker:function(latlng) {
                
                CheckIn.markers.start = new google.maps.Marker({
                    position: latlng,
                    title:"Drag me to your Check-in ",
                    draggable:true,
                    animation: google.maps.Animation.DROP
                });
                
                CheckIn.markers.start.setMap( CheckIn.map );
                google.maps.event.addListener(CheckIn.markers.start, 'dragend', CheckIn.dragStart);
               
                google.maps.event.addListener(CheckIn.markers.start, 'click', function() {
                  CheckIn.infoWin.start.open(CheckIn.map, CheckIn.markers.start);
                });
               
                var geocoder = new google.maps.Geocoder();
                     geocoder.geocode({'latLng': latlng}, CheckIn.address);
 
            },
            
            start:function() {
                
                if (navigator.geolocation) {
                    
                    navigator.geolocation.getCurrentPosition(CheckIn.panTo);
                    
                }else{
                    
                    alert("Geolocation is not supported by this browser.");
                }
                
            },
            
            destination:function(){
              
              
              if (CheckIn.markers.end !== null) {
                 return false;
              }
                CheckIn.markers.end = new google.maps.Marker({
                    position: CheckIn.map.getCenter(),
                    title:"Drag Me To Destination",
                    draggable:true,
                    icon:'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                    animation: google.maps.Animation.DROP
                });
                
                
                google.maps.event.addListener(CheckIn.markers.end, 'click', function() {
                  CheckIn.infoWin.end.open(CheckIn.map, CheckIn.markers.end);
                });
                
                CheckIn.markers.end.setMap( CheckIn.map );
                google.maps.event.addListener(CheckIn.markers.end, 'dragend', CheckIn.dragEnd);
                return true;
            },
            
            dragStart:function(data){    
                CheckIn.action = 'start';
                CheckIn.dragMarker(data);
            },
                        
            dragEnd:function(data){
                CheckIn.action = 'end';
                CheckIn.dragMarker(data);
            },
            
            dragMarker:function(data) {
                CheckIn.panTo({coords:{ latitude:data.latLng.d, longitude:data.latLng.e  }});
            },
            
            update:function(){
            
                var action = $(this).attr('field:action');
                var val = (action == 'start') ? $("#info-canvas-start").val() :  $("#info-canvas-end").val();
                return CheckIn.updateLatLng(val, action);
    
            },
            
           panTo:function(position, address) {
            
               var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
               
               console.log("lat: "+position.coords.latitude+"  long: "+position.coords.longitude);
               
               CheckIn.moveMarker(latlng);
               CheckIn.map.panTo(latlng);
               
               if (address == undefined || address == false) {
                    var geocoder = new google.maps.Geocoder();
                    geocoder.geocode({'latLng': latlng}, CheckIn.address);
               }
               

           },
            
            moveMarker:function(latlng) {
                if (CheckIn.action == 'end') {
                    CheckIn.markers.end.setPosition(latlng);
                }else{
                    CheckIn.markers.start.setPosition(latlng);
                }
                
            },
            
            centerMarkers:function(){
                
               var latlng = CheckIn.map.getCenter();
                CheckIn.markers.start.setPosition(latlng)
                CheckIn.markers.end.setPosition(latlng)
            },
            
            updateLatLng:function(address, action){
                
                CheckIn.Geocoder = new google.maps.Geocoder();
                CheckIn.Geocoder.geocode({'address': address}, CheckIn.OnLatLng);
                CheckIn.action = action;
                
            },
            
            OnLatLng:function(data){
                 console.log(data);
                if (data[0]) {

                    var address = data[0].formatted_address;
                    var el =  CheckIn.action == 'start' ? $("#info-canvas-start") : $("#info-canvas-end");
                    el.attr("field:value", address);
                    el.val(address);
                        
                    var latlng = data[0].geometry.location;
                    CheckIn.panTo({coords:{ latitude:latlng.lat(), longitude:latlng.lng()  }}, true);
                            
                    
                }
                
            },
            
            address:function(results, status) {
                
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                      var ad = results[0].formatted_address;
                      var el = CheckIn.action == 'start' ? $("#info-canvas-start") : $("#info-canvas-end");
                          el.val(ad);
                          el.attr("field:value", ad);
                    }
                }
            },
            
            
            distance:function() {
                
                var start = $("#info-canvas-start").val();
                var end   = $("#info-canvas-end").val();
                
                 $.ajax({
                    type: "POST",
                    url: "/tools/async/distance",
                    data: {start:start, end:end },
                    success: CheckIn.onDistance,
                    dataType: 'json'
                    });
                 
            },
            
            removeDistance:function(){
                
                $(this).closest('tr').remove();
                CheckIn.getTotals();
                
            },
            
            onDistance:function(data) {
            
                if (data.rows[0].elements[0].distance !== undefined) {
                    
                    var res = data.rows[0].elements[0];
                    var el = $("#js-distance-table");
                    var id = el.children().length + 1;
                    var miles  = res.distance.text.replace(/[^0-9.]/gi, "");
                    var template = _.template($("#js-distance-template").html());
                    
                    var params = {
                        id:id,
                        time:res.duration.text,
                        distance:miles,
                        reimbursement: Math.abs(parseFloat(miles) * .20).toFixed(2),
                        point:{a:$("#info-canvas-start").val(), b: $("#info-canvas-end").val()},
                    };
                    var html = template(params);
                    el.append(html);
                    
                    CheckIn.getTotals();
                    
                    
                    //console.log($("#js-distance-toggle").attr('data-action'));
                    
                    if ($("#js-distance-toggle").attr('data-action') == 'down') {
                        var t = _.template($("#js-flash-template").html());
                        $("#js-map-tools").append(t({html:html}));
                            $("#flash-message tbody").fadeOut( 3000, function() {
                                $("#flash-message").remove();
                            });
                    }
                }
            
            },
            
            getTotals:function(){
                
              // reimburse miles
                    
                    var totalMiles = 0;
                    
                    $("span.miles").each(function(){
                        var m = parseFloat($(this).html());    
                        totalMiles += m;
                    });
                    
                    $("#js-distance-total").html(totalMiles.toFixed(2)+" mi.");
                    
                    
                    var totalReimburse = 0.00;
                    $("span.reimburse").each(function(){
                        var r = parseFloat($(this).html());    
                        totalReimburse += r;
                    });
                    
                    $("#total-reimburse").html("$"+totalReimburse.toFixed(2));  
                
            },
            
            
            slideDistanceUp:function() {
                
                var el = $(this);
               if(el.attr('data-action') == 'up'){ 
                  el.attr('data-action', 'down');
                
                $( "#js-miles-distance table" ).fadeOut( "slow", function() {
                  
                  $("#js-distance-toggle").addClass('icon-chevron-down');
                  $("#js-distance-toggle").removeClass('icon-chevron-up');
                  
                 
                 });
                
               }else{
                  el.attr('data-action', 'up');
                  
                $( "#js-miles-distance table" ).fadeIn( "slow", function() {
                  
                  $("#js-distance-toggle").addClass('icon-chevron-up');
                  $("#js-distance-toggle").removeClass('icon-chevron-down');
                 
                 
                 });
                
                
               }
            },

      };
      
      $(function(){
      
        google.maps.event.addDomListener(window, 'load', CheckIn.init);  
        
        });
 
 
      
    </script>
    
    