    <style type="text/css">
    
    .rounded-corners {
        -moz-border-radius: 10px;
       -webkit-border-radius: 10px;
       -khtml-border-radius: 10px;
       border-radius: 10px;
       }
    
     .light-grey{
        
        background-color: #ccc;
        
     }
     
     .light-blue {
        
        background-color:#6699FF;
        
     }
     
     .pad-10px{
        
        padding: 10px;
     }
     
     .bold{
        
        font-weight:bold;
        
     }
      
      .map-canvas{
        height: 500px;
      }

      .info-canvas{
        
            background-color: #f6f6f6;
            min-height: 30px;
            max-height: 50px;
            overflow: auto;
            width: 100%;
            padding: 5px;
            z-index: 1001;
            position: absolute;
            top: 0px;
            left: 0px;
        }
        .js-miles, .js-miles-bg {
            z-index: 1003;
            position: absolute;
            height: 50px;
            top: 70px;
            left: 85px;
            width:85%   ;
        }
        
        .js-miles-bg {
            background-color: #555;          
            opacity:0.3;
            filter:alpha(opacity=30); /* For IE8 and earlier */
        }
    
        
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLH9g4xG6aB3qiAHyyJXyJXsRGhv0wBnw&sensor=true&region=us"> </script>
    
    <div id="info-canvas" class="info-canvas">
        
        <a class="pointer js-current-position bold">Current Postion</a>: 
        
        <span id="info-canvas-start"
            class="pointer js-click-to-update light-grey pad-10px"
            field:type="text"
            field:name="js-current-value-start"
            field:value=""
            field:action="start"
            field:length="255"> </span>
        
        <br />
        
        
        <span id="info-canvas-end"
            class="pointer js-click-to-update light-blue pad-10px" 
            field:type="text" 
            field:name="js-current-value-end" 
            field:action="end" 
            field:value="" 
            field:length="255"> </span>
        
        <br />
        <a class="pointer js-distance-calc">Get Distance Info </a>
        
        
        
    </div>
    
     <div id="js-miles-bg" class="js-miles-bg"></div>
     <div id="js-miles" class="js-miles">
        
        <input type="button" value="Drop Pin" class="pointer js-current-destination bold" /> 
        
        
     </div>
     
     <div id="map-canvas" class="map-canvas" > </div>
    
    <script type="text/javascript">
 
        
      var CheckIn = {

            map:null,
            markers:{start:null, end:null},
            action:'start',
            coords: {lat:0, lng:0},
            
            init:function() {
            
            
                        navigator.geolocation.getCurrentPosition(function(coords){
                            
                            console.log(position);
                            
                            
                            });
                        
                        return;
            
                    if (navigator.geolocation) {
                    
                    navigator.geolocation.getCurrentPosition(CheckIn.buildMap);
                    
                }else{
                    
                    alert("Geolocation is not supported by this browser.");
                }
                            
                
                
            },
            
            noPosi:function(err){
                
                console.log(err);
            },
                           
            
            buildMap:function(position) {
                
                
                console.log("posi: "+position.coords.latitude);
                
                return; 
                var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

                var options = {
                        center: latlng,
                        zoom: 14,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };
                
                CheckIn.map = new google.maps.Map(document.getElementById("map-canvas"), options);
                CheckIn.appendStartMarker(latlng);
                
                $('body').delegate(".js-click-to-update", "click", CheckIn.update);
                $('body').delegate(".js-current-value-update-btn", "click", CheckIn.updateLatLng);
                
                $('.js-current-position').click(CheckIn.start);
                $('.js-current-destination').click(CheckIn.destination);
                $('.js-distance-calc').click(CheckIn.distance);
                
                
            },
            
            appendStartMarker:function(latlng) {
                
                CheckIn.markers.start = new google.maps.Marker({
                    position: latlng,
                    title:"Drag me to your Check-in ",
                    draggable:true,
                    animation: google.maps.Animation.DROP
                });
                
                CheckIn.markers.start.setMap( CheckIn.map );
                google.maps.event.addListener(CheckIn.markers.start, 'dragend', CheckIn.dragStart);
                
                 var geocoder = new google.maps.Geocoder();
                     geocoder.geocode({'latLng': latlng}, CheckIn.address);
 
            },
            
            start:function() {
                
                if (navigator.geolocation) {
                    
                    navigator.geolocation.getCurrentPosition(CheckIn.panTo);
                    
                }else{
                    
                    alert("Geolocation is not supported by this browser.");
                }
                
            },
            
            destination:function(){
              
              
              if (CheckIn.markers.end !== null) {
                 return false;
              }
                
              var lat = '38.72993436850347';
              var lng = '-120.80449479198455';
              var myLatlng = new google.maps.LatLng(lat, lng);
                
                CheckIn.markers.end = new google.maps.Marker({
                    position: myLatlng,
                    title:"Drag Me To Destination",
                    draggable:true,
                    icon:'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                    animation: google.maps.Animation.DROP
                });
                
                CheckIn.markers.end.setMap( CheckIn.map );
                google.maps.event.addListener(CheckIn.markers.end, 'dragend', CheckIn.dragEnd);
                return true;
            },
            
            dragStart:function(data){    
                CheckIn.action = 'start';
                CheckIn.dragMarker(data);
            },
                        
            dragEnd:function(data){
                CheckIn.action = 'end';
                CheckIn.dragMarker(data);
            },
            
            dragMarker:function(data) {
                CheckIn.panTo({coords:{ latitude:data.latLng.lb, longitude:data.latLng.mb  }});
            },
            
            update:function(){
                
                var el = $(this);
                
                if ( $("#"+el.attr('id')+" .js-current-value-update-btn").size() != 0 ) {
                    return false;
                }
                
                CheckIn.action = el.attr("field:action");
                
                var field = { type: el.attr("field:type"),
                              name: el.attr("field:name"),
                              id: el.attr("field:name"),
                              maxlength: el.attr("field:length"),
                              value: el.attr("field:value"),
                              class: 'js-click-to-value',
                              width:300
                              };
                
                var btn = {
                    value:"update",
                    type:"button",
                    class:"js-current-value-update-btn pointer",
                    "data:node":el.attr('id'),
                    "data:action":el.attr('action')
                };
                
                el.html( $('<input/>', field) );
                el.append($('<input/>', btn));
                
                return true;         
 
                
            },
            
           panTo:function(position, noAddress) {
            
               var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
               
               CheckIn.moveMarker(latlng);
               CheckIn.map.panTo(latlng);
               
               if (noAddress == undefined || noAddress == false) {
                    var geocoder = new google.maps.Geocoder();
                    geocoder.geocode({'latLng': latlng}, CheckIn.address);
               }
               

           },
            
            moveMarker:function(latlng) {
                
                console.log(CheckIn.action );
                
                if (CheckIn.action == 'end') {
                    CheckIn.markers.end.setPosition(latlng);
                }else{
                    CheckIn.markers.start.setPosition(latlng)
                }
                
                
            },
            
            updateLatLng:function(){
                var el = $(this);
                var node = el.attr("data:node");
                var address = $("#"+node+" .js-click-to-value").val();
                
                CheckIn.Geocoder = new google.maps.Geocoder();
                CheckIn.Geocoder.geocode({'address': address}, CheckIn.OnLatLng);
                CheckIn.action = el.attr("data:action");
                
            },
            
            OnLatLng:function(data){
                 
                if (data[0]) {

                    var address = data[0].formatted_address;
                    var el =  CheckIn.action == 'start' ? $("#info-canvas-start") : $("#info-canvas-end");
                        el.attr("field:value", address);
                        el.html(address);
                
                    var laglng = data[0].geometry.location;
                    CheckIn.panTo({coords:{ latitude:laglng.lb, longitude:laglng.mb  }}, true);
                    
                }
                
            },
            
            address:function(results, status) {
                
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                      var ad = results[0].formatted_address;
                      var el = CheckIn.action == 'start' ? $("#info-canvas-start") : $("#info-canvas-end");
                          el.html(ad);
                          el.attr("field:value", ad);
                    }
                }
            },
            
            
            distance:function() {
                
                var start = $("#info-canvas-start").html();
                var end   = $("#info-canvas-end").html();
                
               
                 $.ajax({
                    type: "POST",
                    url: "/tools/async/distance",
                    data: {start:$("#info-canvas-start").html(), end:$("#info-canvas-end").html()},
                    success: CheckIn.onDistance,
                    dataType: 'json'
                    });
                 
            },
            
            
            onDistance:function(data) {
            
                if (data.rows[0].elements[0].distance !== undefined) {
                    
                    var res = data.rows[0].elements[0];
                    var html = "";
                        html += res.distance.text;
                        html += "<br />" + res.duration.text
                    
                     var miles   = res.distance.text.replace(/[^0-9.]/gi, "");
                     var dollars = Math.abs(parseFloat(miles) * .20);   
                     html += " Re: $"+dollars.toFixed(2);
                     $("#js-miles").html(html);
                    
                }
            
            }

      };
      
      $(function(){
      
        google.maps.event.addDomListener(window, 'load', CheckIn.init);  
        
        });
 
 
      
    </script>
    
    
