<h4>If consumer was hospitalized or taken to the Emergency Room</h4>

<div class="crud-create-update crud-load-template pointer hidden"
    id="hospital-bind-crud"
    data-id=''
    data-path='.:hospitalized'
    data-form='consumerhospitalizedform'
    data-title="Edit Hospital Visits"
    data-params=''
    data-action='create'
    data-target='js-hospital-index'
    data-template='js-crud-edit-hospital'
    data-callback='lightBox.dateFields'></div>

<?= $this->TableHead( array("Hospital",
                            "Reasion",
                            "Date",
                            "Duration of Stay",
                            "Edit",
                            "Delete" ), "table table-bordered js-hospital-index", "js-hospital-index" ) ?>
	   
    <?if(isset($this->hospitalized)):?>
       <?foreach($this->hospitalized as $k=>$v):?>
        <?= $this->TableRow(array( $this->escape($v->hospital),
                                   $this->escape($v->reason),
                                   $this->escape($v->date),
                                   $this->escape($v->duration_of_stay),
                                   "<center>
                                   <a class='crud-create-update icon icon-edit'
                                      data-action='update'
                                      data-bind='hospital-bind-crud'
                                      data-params='id:{$v->id}'></a>
                                   </center>",
                                   "<center>
                                   <a class='crud-delete icon icon-remove' data-bind='hospital-bind-crud' data-params='id:{$v->id}'></a>
                                   </center>"), "class='crud-row-{$v->id} highlight-child'"); ?>
       
       <?endforeach;?>
   <?endif;?>
	   
    <?= $this->TableFoot("<tr><td colspan='6'><a class='crud-create-update pull-right'
                                                        data-action='create'
                                                        data-bind='hospital-bind-crud'
                                                        data-params='consumer_id:{$this->consumer_id}'>Add Hospital Visit
                                                     </a></td></tr>" ) ?>

<script type="text/plain" id="js-crud-edit-hospital">
	<% if( action == 'create' ){%>
            <tr class="crud-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	
        <td><%= helpers.escapeHtml(values.hospital) %></td>
	<td><%= helpers.escapeHtml(values.reason) %></td>
        <td><%= helpers.escapeHtml(values.date) %></td>
	<td><%= helpers.escapeHtml(values.duration_of_stay) %></td>
        <td>
            <center>
            <a class='crud-create-update icon icon-edit'
               data-action='update'
               data-bind='hospital-bind-crud'
               data-params='id:<%= helpers.escapeHtml(id) %>'></a>
            </center>
        </td>

        <td>
            <center>
            <a class='crud-delete icon icon-remove'
               data-bind='hospital-bind-crud'
               data-params='id:<%= helpers.escapeHtml(id) %>'></a>
            </center>            
        </td>
        
        <% if( action == 'create' ){ %>
            </tr>
	<% } %>
</script>



















