<?php
$this->headScript()->appendFile('/js/vendor/date-format.js');
$this->headLink()->appendStylesheet('/css/views/default/index.css');
?>

<div class="row">
    
<div class="span3">    

    <ul class="rounded-corners tools">
        <li class="tools-header">Tools:</li>
        <li><a class="js-tool-click pointer" data:url="/tools/milesab" >A to B Mileage Tool</a></li>
    </ul>
    
    

    <hr />

    <ul class="rounded-corners tools">
    <li class="tools-header">My People:</li>
    <?foreach( $this->consumers as $consumer ):?>
        <li> <img src="/img/src/<?=$consumer->id?>/c" width="50px" />
            <a class="pointer" href="/consumer/view/<?=$consumer->id?>" ><?=$consumer->fname?> <?=$consumer->lname?></a>
            <div id="med-appointments-<?=$consumer->id?>">
                
            </div>
            
            
        </li>
    <?endforeach;?>
    </ul>

</div>


<div class="span8">    

    
    <?= $this->partial( '/partials/widgets.phtml', 'tools', array( ) );
    ?>
 
    <?= $this->partial( '/partials/chat.phtml', 'tools',   array( "messages"=>$this->messages )  ); ?>

    
 </div>   
    
</div>



<script>
    
    
    $(function(){
    $(".js-tool-click").click(function(){
        
        var el = $(this);
        var ul = el.attr('data:url');
           window.open(ul, "popupWindow", "width=600,height=600,scrollbars=yes");
 
        });
    
    
    content.load('/messages/appontments', {}, function(data){            
        var template = _.template($("#appontments-this-week-template").html());
        for (var key in data) {
             var app = data[key];
             $("#med-appointments-"+app.consumer_id).append(template(app)).promise().done(function() {
                 helpers.popover(app.id); 
             });
        }}, 'json');
    });
    
    
    
</script>


<script id="appontments-this-week-template" type="text/plain">
    <li class="pointer"
        rel="popover"
        data-html='true'
        data-content="<%=hospital%><hr> <span class='alert alert-success'>
        <%= helpers.formatDate(date, 'mmm, ddd dS') %> <%= time %> <%= ampm %></span> <hr> <%= description %> "
        data-original-title="Medical Appointment"
        id="popover-<%= id %>">
        <small>
        <%= hospital.substring(0, 10) %> <%= helpers.formatDate(date, 'mmm, ddd dS') %> <%= time %> <%= ampm %>
        </small>
   </li>
</script>
