<div id="js-consumer-pharmaceuticals-info"> </div>

<div id="js-consumer-pharmaceuticals-btns">
<? foreach( $this->pharmaceuticals as $p ):?>

    <?if( in_array( $p['id'], $this->assignedIds ) ): 
        $status = "Assigned";
        $style  = "btn-success";
        $vis    = array( 'assign'=>'hidden', 'remove'=>'' );
    else: 
        $status = "Unassigned";
        $style  = "btn-warning";
        $vis    = array( 'assign'=>'', 'remove'=>'hidden' );
    endif;?>
    
    
    <div id="pharmaceutical_<?=$p['id']?>" pharmaceutical:name="<?=$p['name']?>"  pharmaceutical:phone="<?=$p['mg']?>"  class="btn-group" title="<?=$status?>">
    
    <a class="js-assign-to-consumer-btn btn btn-primary <?=$style?> js-append-info-to pointer" 
        pharmaceutical:id="<?=$p['id']?>"
        append:id="<?=$p['id']?>",
        append:url="/pharmaceuticals/read/id/"                         
        append:div="js-consumer-pharmaceuticals-info"><i class="icon-user icon-white"></i> <?=$p['name']?></a>
   
    <a class="js-assign-to-consumer-btn btn btn-primary <?=$style?> dropdown-toggle" 
       data-toggle="dropdown" 
       href="#"><span class="caret"></span></a>
     
    <ul class="dropdown-menu">
        <li class="<?=$vis['remove']?> js-pharmaceutical-remove-link" 
            consumer:id="<?=$this->id?>" 
            consumer:pharmaceutical="<?=$p['id']?>"><a class="pointer js-assign-to-consumer" 
            consumer:action="remove"><i class="icon-trash"></i> Remove</a></li>

        <li class="<?=$vis['assign']?> js-pharmaceutical-assign-link" 
            consumer:id="<?=$this->id?>" 
            consumer:pharmaceutical="<?=$p['id']?>"><a class="pointer js-assign-to-consumer" 
            consumer:action="assign"><i class="icon-thumbs-up"></i> Assign</a></li>    
    </ul>
    
    </div>
        
    
<?endforeach;?>
</div>
