<?
$this->headScript()->appendFile('/js/views/consumer/insurance/index.js');

/*
   * `id`,
   * `consumer_id`,
   * `type`,
   * `medical_number`,
   * `medicare_number`,
   * `insurance_info`
*/
?>

<h2>Insurance Info</h2>

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/insurance/new/', 'label'=>'Add New')) ?>
<hr />

<? if(isset( $this->insurance )): ?>

    <?= $this->TableHead( array("Type",
                                "Medical #",
                                "Medicare #",
                                "Info",
                                "Delete"), "table table-striped" ) ?>
  
    <?foreach($this->insurance as $i):?>
        <?= $this->TableRow(array( "<a href='/consumer/insurance/edit/id/".$i["id"]."'>".$i["type"]."</a>",
                                   $i["medical_number"],
                                   $i["medicare_number"],
                                   $i["insurance_info"],
                                   "<a id='insurance-".$i["id"]."'
                                   class='pointer del-insurance' data-id='".$i["id"]."' title='delete'><i class='icon-remove'></i></a>")); ?>
    <?endforeach;?>
    
    <?= $this->TableFoot() ?>
<?endif;?>

<hr />

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/insurance/new/', 'label'=>'Add New')) ?>


