
<script id="js-notes-template" type="text/plain">
    <tr class="consumer-note-<%= id %>">
        <td><span class="js-edit-note-text pointer" data-id="<%= id %>"><%= note %></span></td>
        <td class="date-created"><%= created %></td>
        <td><i class="note-del icon icon-remove pointer" data-id='<%= id %>'></i></td>
    </tr>    
</script>


<script id="js-notes-edit-template" type="text/plain">
        <form id="update-note-<%= id %>">
            <textarea name="note" class="textarea-standard-size"><%= note %></textarea><br />
            <input name="id" type="hidden" value="<%= id %>" />
            <input name="consumer_id" type="hidden" value="<%= consumer_id %>" />
            <input name="user_id" type="hidden" value="<%= user_id %>" />
            <input type="button" class="btn btn-primary update-note-sub" data-id="<%= id %>" value="Update Note" />
            <pre   id="note-undo-<%= id %>" class="hidden"><%= note %></pre>
            <input id="update-note-cancel-<%= id %>" data-id="<%= id %>" type="button" class="btn update-note-cancel" value="Cancel" />
        </form>
</script>

<script id="js-notes-text-template" type="text/plain">
    <span class="js-edit-note-text pointer" data-id="<%= id %>"><%= note %></span>
</script>



<div class="well">
    <label id="js-add-note-info" for="note"><strong>Create a note for todays date: <?=date('m-d-Y')?></strong></label>
    <form id="js-add-new-note">
        <textarea id="note" name="note" class="textarea-standard-size"></textarea><br />
        <input id="consumer_id" name="consumer_id" type="hidden" value="<?=$this->consumer->id?>" />
        <input id="user_id" name="user_id" type="hidden" value="<?=$this->user_id?>" />
        <input id="created" name="created" type="hidden" value="<?=date('Y-m-d')?>">
        <input id="new-note-sub" type="button" class="btn btn-primary" value="Add Note" />
    </form>
</div>
<div id="js-show-all-notes-for-year-month"> </div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Note</th>
            <th>Created</th>
            <th>Delete</th>
        </tr>
    </thead>
    
    <tbody id="js-case-note-data">
                        
    </tbody>
    
</table>
