<ul class="rounded-corners tools">
    <li class="tools-header">Actons:</li>
    <li><a href="/appointment/index/cid/<?=$this->consumer->id?>">Add Appointment</a></li>
    <li><a class="pointer js-assign-physician" consumer:id="<?=$this->consumer->id?>"> Assign Physician</a></li>
    <li><a class="pointer js-assign-pharmaceutical" consumer:id="<?=$this->consumer->id?>"> Assign Medication</a></li>
</ul>