
<script id="js-notes-template" type="text/plain">
    <tr class="consumer-note-<%= helpers.escapeHtml(id) %>">
        <td><span class="js-edit-note-text pointer"
                  data-id="<%= helpers.escapeHtml(id) %>"
                  data-goal_id="<%= helpers.escapeHtml(goal_id) %>" 
                  data-goal="<%= helpers.escapeHtml(goal) %>"> 
                  <%= helpers.escapeHtml(note) %></span></td>
        <td class="date-created"><%= helpers.escapeHtml(created) %></td>
        <td><%= helpers.escapeHtml(goal) %></td>
        <td><i class="note-del icon icon-remove pointer" data-id='<%= helpers.escapeHtml(id) %>'></i></td>
    </tr>    
</script>


<script id="js-note-update-template" type="text/plain">
  
    <td><span class="js-edit-note-text pointer"
          data-id="<%= helpers.escapeHtml(id) %>"
          data-goal_id="<%= helpers.escapeHtml(goal_id) %>" 
          data-goal="<%= helpers.escapeHtml(goal) %>"> 
          <%= helpers.escapeHtml(note) %></span></td>
<td class="date-created"><%= helpers.escapeHtml(created) %></td>
<td><%= helpers.escapeHtml(goal) %></td>
<td><i class="note-del icon icon-remove pointer" data-id='<%= id) %>'></i></td>
    
</script>

<script id="js-notes-edit-template" type="text/plain">
        <form id="update-note-<%= id %>">
            
            <div id="goal-input">
                <label for="goal-to-notes-update-<%= id %>">Objective/Goal:</label>
                <input type="text" name="goal-to-notes-update-<%= helpers.escapeHtml(id) %>"
                       data-append="-update-<%= helpers.escapeHtml(id) %>"
                       data-form="update-note-<%= helpers.escapeHtml(id) %>"
                       data-value="<%= helpers.escapeHtml(goal) %>"
                       id="goal-to-notes-update-<%= helpers.escapeHtml(id) %>"
                       class="goal-to-notes" value="<%= helpers.escapeHtml(goal) %>"/><br />
                
                <div class="dropdown">
                    <ul id="js-goals-suggestions-select-update-<%= helpers.escapeHtml(id) %>" class="dropdown-menu" role="menu" aria-labelledby="dLabel"> </ul>
                </div>
                
            </div>
            
            <label for="note-update-<%= helpers.escapeHtml(id)%>">Note:</label>
            <textarea name="note-update-<%= helpers.escapeHtml(id) %>" class="textarea-standard-size"><%= helpers.escapeHtml(note) %></textarea><br />
            <input name="id-update-<%= id %>" type="hidden" value="<%= id %>" />
            <input name="consumer_id-update-<%= id %>" type="hidden" value="<%= consumer_id %>" />
            <input name="user_id-update-<%= id %>" type="hidden" value="<%= user_id %>" />
            <input name="goal_id-update-<%= id %>" id="goal_id-update-<%= id %>" type="hidden" value="<%= goal_id %>" class="goal_id"  />
            <input type="button" class="btn btn-primary update-note-sub" data-id="<%= id %>" value="Update Note" />
            <pre   id="note-undo-<%= id %>" class="hidden">
             <span class="js-edit-note-text pointer"
            data-id="<%= id %>"
            data-goal_id="<%= helpers.escapeHtml(goal_id) %>" 
            data-goal="<%= helpers.escapeHtml(goal) %>"> 
            <%= note %></span>
            </pre>
            <input id="update-note-cancel-<%= id %>" data-id="<%= id %>" type="button" class="btn update-note-cancel" value="Cancel" />
        </form>
</script>

<script id="js-notes-text-template" type="text/plain">
    
    <span class="js-edit-note-text pointer"
          data-id="<%= id %>"
          data-goal_id="<%= goal_id %>" 
          data-goal="<%= helpers.escapeHtml(goal) %>"> 
          <%= helpers.escapeHtml(note) %></span>
</script>



<div class="well">
    <label id="js-add-note-info" for="note"><strong>Create a note for todays date: <?=date('m-d-Y')?></strong></label>
    <form id="js-add-new-note">
        
        <div id="goal-input">
        
            <label for="goal-to-notes">Objective/Goal:</label>
            <input type="text" name="goal-to-notes"
                   id="goal-to-notes"
                   data-form="js-add-new-note"
                   data-append="-create"
                   class="goal-to-notes" value=""/><br />
            
            <div class="dropdown">
            <ul id="js-goals-suggestions-select-create" class="dropdown-menu" role="menu" aria-labelledby="dLabel"> </ul>
            </div>
        
        </div>
        
        <label for="note">Note:</label>
        <textarea id="note" name="note" class="textarea-standard-size"></textarea><br />
        <input id="consumer_id" name="consumer_id" type="hidden" value="<?=$this->consumer->id?>" />
        <input id="user_id" name="user_id" type="hidden" value="<?=$this->user_id?>" />
        <input name="goal_id" id="goal_id" type="hidden" value="" />
        <input id="created" name="created" type="hidden" value="<?=date('Y-m-d')?>">
        <input id="new-note-sub" type="button" class="btn btn-primary" value="Add Note" />
    </form>
</div>
<div id="js-show-all-notes-for-year-month"> </div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Note</th>
            <th>Created</th>
            <th>Goal</th>
            <th>Delete</th>
        </tr>
    </thead>
    
    <tbody id="js-case-note-data">
                        
    </tbody>
    
</table>
