<ul class="rounded-corners tools">
    <li class="tools-header">Actons:</li>
    <li><a href="/consumer/medical/appointment/<?=$this->consumer->id?>">Add Appointment</a></li>
    <li><a class="pointer js-assign-physician" consumer:id="<?=$this->consumer->id?>"> Assign Physician</a></li>
    <li><a class="pointer js-assign-pharamchical" consumer:id="<?=$this->consumer->id?>"> Assign Medication</a></li>
</ul>