<ul class="rounded-corners tools">
    <li class="tools-header">Actons:</li>
    <?foreach($this->links as $label=>$link):?>
        <li>
            <a <?=isset($link['href']) ? "href=".$link['href'] : "" ?> <?= isset($link['class']) ?  "class='".$link['class']."'" : ""?> <?= isset($link['attr']) ?  $link['attr'] : ""?>>
                <?=$label?>
            </a>
        </li>
    <?endforeach;?>
</ul>