

<?if(!$this->word):?>

<? $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                         'back'=>'/isp/summary',
                                                         'id' => $this->consumer->id,
                                                         'next'=>false,
                                                         'formName'=>$this->formName,
                                                         'steps'=>$this->steps,
                                                         'activeStep'=>$this->activeStep));
                                                         ?>


<a href="/isp/finalize/id/<?=$this->consumer->id?>/word/true" class="btn"> Export as Word Doc</a>

<?endif;?>

<?= $this->partial("/isp/partials/isp-report-template.phtml", array('header'=>true,
                                                                    'consumer'=>$this->consumer,
                                                                    'user'=>$this->user,
                                                                    'persons'=>$this->persons,
                                                                    'coordinator'=>$this->coordinator,
                                                                    'exams'=>$this->exams,
                                                                    'insurance'=>$this->insurance,
                                                                    'medications'=>$this->medications,
                                                                    'allergies'=>$this->allergies,
                                                                    'hospitalized'=>$this->hospitalized,
                                                                    'medicalStatus'=>$this->medicalStatus,
                                                                    'sirs'=>$this->sirs,
                                                                    'programs'=>$this->programs,
                                                                    'goals'=>$this->goals,
                                                                    'data'=>$this->data)); ?>

