<?if(!$this->showHeader):?>

<form action="#" method="post" id="isp-gen-final" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/summary',
                                                             'id' => $this->consumer->id,
                                                             'next'=>false,
                                                             'customNext'=>"<a href='/isp/finalize/id/{$this->consumer->id}/word/true' class='btn neg-margin-top-10'>Export Word Doc &gt;&gt;</a>",
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
</form>

<?if(!$this->showHeader):?>
<div class="" style="margin-left:200px;">                                                         
<?endif;?>


<?endif;?>

<?= $this->partial("/isp/partials/isp-report-template.phtml", array('header'=>$this->showHeader,
                                                                    'consumer'=>$this->consumer,
                                                                    'user'=>$this->user,
                                                                    'persons'=>$this->persons,
                                                                    'coordinator'=>$this->coordinator,
                                                                    'exams'=>$this->exams,
                                                                    'insurance'=>$this->insurance,
                                                                    'medications'=>$this->medications,
                                                                    'allergies'=>$this->allergies,
                                                                    'hospitalized'=>$this->hospitalized,
                                                                    'medicalStatus'=>$this->medicalStatus,
                                                                    'sirs'=>$this->sirs,
                                                                    'programs'=>$this->programs,
                                                                    'goals'=>$this->goals,
                                                                    'data'=>$this->data)); ?>

<?if(!$this->showHeader):?>
</div>
<?endif;?>

