
<form action="/isp/programs" method="post" id="isp-gen-goals" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/sirs',
                                                             'id' => $this->consumer->id,
                                                             'next'=>true,
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
    
    <div class="row">
        <div class="span12">
           <div class="well">
                
                <strong>Update Goals Info for <?=$this->consumer->fname?> <?=$this->consumer->lname?> </strong>
                        <?= $this->partial( "/goals/partials/crud.phtml", 'consumer',
                            array( "goals"=>$this->goals,
                                   "consumer_id"=>$this->consumer->id) );?>    
                
                <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
           </div>
        </div>
    </div>

</form>