<form action="/isp/info" method="post">
<?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                         'next'=>true,
                                                         'formName'=>$this->formName,
                                                         'steps'=>$this->steps,
                                                         'activeStep'=>$this->activeStep,
                                                         'id'=>$this->id)); ?>
<div class="row">
    <div class="span12">
        <div class="well">
        <fieldset>
        <legend>Please select a Consumer to start your ISP Report</legend>
        <ul class="no-bullet">
                                                         
            <?if(isset($this->consumers)):?>                                             
            <?foreach( $this->consumers as $consumer ):?>
                <?$checked = (isset($this->id) && $this->id == $consumer->id) ? 'checked="checked"' : '';?>
                <li class="pad-5px">
                    <label class="radio">
                    <input name="id" <?=$checked?> type="radio" value="<?=$consumer->id?>"> <?=$consumer->fname?> <?=$consumer->lname?>
                    </label>
                </li>
            <?endforeach;?>
            <?endif;?>
        </ul>        
        </fieldset>
       </div>
    </div>
</div>

<?if(isset($this->consumers) && count($this->consumers) > 10):?>                                                         
<div class="row">
    <input type="submit" class="btn btn-success pull-right neg-margin-top-10" value="Next &gt;&gt;">
</div>    
<?endif;?>    
</form>