<?
$this->headScript()->appendFile('/js/vendor/bootstrap-datepicker.js');
$this->headScript()->appendFile('/js/views/reports/isp/medical.js');
$this->headLink()->appendStylesheet('/css/datepicker.css');
?>

<form action="/isp/goals" method="post" id="isp-gen-medical" >

<?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                         'back'=>'/isp/info',
                                                         'id' => $this->consumer->id,
                                                         'next'=>true,
                                                         'formName'=>$this->formName,
                                                         'steps'=>$this->steps,
                                                         'activeStep'=>$this->activeStep)); ?>
<div class="row">
<div class="span12">
<div class="well">

<input type="hidden" name="id" value="<?=$this->consumer->id?>" />
		
	<?= $this->partial( "/isp/partials/medical-exams.phtml",
						   array( "physicians"=>$this->physicians,
								  "consumer_id"=>$this->consumer->id) );?>
	<hr />
	<?= $this->partial( "/isp/partials/medical-insurance.phtml",
						   array( "insurance"=>$this->insurance,
								  "consumer_id"=>$this->consumer->id) );?>								
	<hr />
	<?= $this->partial( "/isp/partials/medical-medications.phtml",
						   array( "medications"=>$this->medications,
								  "consumer_id"=>$this->consumer->id) );?>

	<hr />
	<?= $this->partial( "/isp/partials/medical-allergies.phtml",
						   array( "allergies"=>$this->allergies,
								  "consumer_id"=>$this->consumer->id) );?>
	
	<hr />
	<?= $this->partial( "/isp/partials/medical-hospitalized.phtml",
						   array( "hospitalized"=>$this->hospitalized,
								  "consumer_id"=>$this->consumer->id) );?>
	
	
	<hr />
	<?= $this->partial( "/isp/partials/medical-health.phtml",
						   array( "consumer_id"=>$this->consumer->id) );?>
	
	

	
</div>
</div> 
</div>
</form>