<?
$this->headScript()->appendFile('/js/views/reports/isp/medical.js');
$this->headScript()->appendFile('/js/views/consumer/exam/crud.js');
?>

<form action="/isp/goals" method="post" id="isp-gen-medical" >

<?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                         'back'=>'/isp/info',
                                                         'id' => $this->consumer->id,
                                                         'next'=>true,
                                                         'formName'=>$this->formName,
                                                         'steps'=>$this->steps,
                                                         'activeStep'=>$this->activeStep)); ?>
<div class="row">
<div class="span12">
<div class="well">

<input type="hidden" name="id" value="<?=$this->consumer->id?>" />
		
        <?= $this->partial( "/exam/partials/crud.phtml", 'consumer',
                        array( "physiciansExams"=>$this->physicians,
                              "selectBoxs"=>true,
                               "consumer_id"=>$this->consumer->id) );?>
        <hr />
        
        <?= $this->partial('/insurance/partials/crud.phtml', 'consumer',
                        array( "insurance"=>$this->insurance,
                              "consumer_id"=>$this->consumer->id));?>           
        
        <hr />                                                                  
        <?= $this->partial('/medication/partials/crud.phtml', 'consumer',
                        array( "medications"=>$this->medications,
                              "consumer_id"=>$this->consumer->id));?>                                                          
        
        
        <hr />
        <?= $this->partial( "/allergies/partials/crud.phtml", 'consumer',
                        array( "allergies"=>$this->allergies,
                              "consumer_id"=>$this->consumer->id) );?>
        
        <hr />
        <?= $this->partial( "/hospitalized/partials/crud.phtml", 'consumer',
                        array( "hospitalized"=>$this->hospitalized,
                              "consumer_id"=>$this->consumer->id) );?>
        
        
        <hr />
        <?= $this->partial( "/isp/partials/medical-health.phtml",
                        array( "consumer_id"=>$this->consumer->id) );?>
	

	
</div>
</div> 
</div>
</form>