<?
$this->headScript()->appendFile('/js/vendor/bootstrap-datepicker.js');
$this->headScript()->appendFile('/js/views/reports/isp/medical.js');
$this->headLink()->appendStylesheet('/css/datepicker.css');

?>
<form action="/isp/goals" method="post" id="isp-gen-medical" >
<?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                         'back'=>'/isp/info',
                                                         'id' => $this->consumer->id,
                                                         'next'=>true,
                                                         'formName'=>$this->formName,
                                                         'steps'=>$this->steps,
                                                         'activeStep'=>$this->activeStep)); ?>
<div class="row">
    <div class="span12">
       <div class="well">
       <h3>Medical Information for <?=$this->consumer->fname?> <?=$this->consumer->lname?> </h3>
       
	   <table class="table table-striped">
		<thead>
			<tr>
				<th>Insurance Type</th>
				<th>Medical #</th>
				<th>Medicare #</th>
				<th>Information</th>
			</tr>
		</thead>
	   <tbody>
		
		<?foreach($this->insurance as $k=>$i):?>
			<tr>
			<td><?=$i['type']?></td>
			<td><?=$i['medical_number']?></td>
			<td><?=$i['medicare_number']?></td>
			<td><?=$i['insurance_info']?></td>
			</tr>
		<?endforeach;?>
	   </tbody>
	   </table>
	   <hr />
	   
	   
	   <strong>Select Exam information for <?=$this->consumer->fname?> <?=$this->consumer->lname?> </strong>
       <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
	   <a class=" pointer crud-new-update-med btn btn-primary pull-right"
		  data-cid="<?=$this->consumer->id?>" data-id=''> Add Info <i class="icon-plus"></i> </a>
	   <hr />
	   
	   <div class="max-height-450px overflow-auto">
	   
<? if(isset( $this->physicians )): ?>
    <?= $this->TableHead( array("Physician Name",
                                "Address",
                                "Phone",
                                "Exam Type",
                                "Date of Last Exam",
                                "Result of Exam",
                                "Select",
                                "Edit",
                                "Delete" ), "table table-bordered js-med-index" ) ?>
    <?foreach($this->physicians as $p):?>
    <?foreach($p['exams'] as $e):
	 $strDate = strtotime( $e->date );
	?>
        <?= $this->TableRow(array( $this->Truncate($p["name"], 30),
                                   $this->Truncate($p["address"], 30),
                                   $p["phone"],
                                   $e->type,
                                   date('m/d/Y', $strDate ),
                                   "<div class='show-tooltip' title='".$this->escape($e->result)."' data-toggle='tooltip' >".$this->Truncate($e->result, 30)."</div>",
                                   "<center><input type='checkbox' name='exams[]' value='{$e->id}' /></center>",
                                   "<center><a class='pointer crud-new-update-med' data-id='{$e->id}' data-cid='{$this->consumer->id}'><i class='icon-edit'></i></a></center>",
                                   "<center><a id='med-{$e->id}'
                                   class='pointer crud-del-med' data-id='{$e->id}' data-cid='{$this->consumer->id}' title='delete'><i class='icon-remove'></i></a></center>",
                                   ), "class='exam-row-{$e->id} highlight-child'"); ?>
    <?endforeach;?>
    <?endforeach;?> 
    <?= $this->TableFoot() ?>
<?endif;?>

</div>

	   <a class=" pointer crud-new-update-med btn btn-primary pull-right"
		  data-cid="<?=$this->consumer->id?>" data-id=''> Add Exam Info <i class="icon-plus"></i> </a>

     </div>
    </div>
    
</div>

</form>
<script type="text/javascript">
    $(function () {
        $(".show-tooltip").tooltip();
    });
</script>


<script type="text/plain" id="js-crud-edit-med">	
	
	<td><%= physician.name.substring(0, 30)%></td>
	<td><%= physician.address.substring(0, 30)%></td>
	<td><%= physician.phone %></td>
	<td><%= values.type %></td>
	<td><%= values.date %></td>
	<td><div title="<%=values.result%>"><%=values.result.substring(0, 30)  %></div></td>
        <td><center><input type='checkbox' name='exams[]' value='<%= values.id %>' /></center></td>
	<td><center><a class='pointer crud-new-update-med' data-id='<%= values.id %>' data-cid='<%= consumer_id %>'><i class='icon-edit'></i></a></center></td>
	<td><center><a title="delete" data-cid="<%= consumer_id %>" data-id="<%= values.id %>"
		   class="pointer crud-del-med" id="med-<%= values.id %>"><i class="icon-remove"></i></a></center></td>
	
</script>
