               
<form action="/isp/summary" method="post" id="isp-gen-projects" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/goals',
                                                             'id' => $this->consumer->id,
                                                             'next'=>true,
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
    
    <div class="row">
        <div class="span12">
           <div class="well">
                
              <?= $this->partial( "/program/partials/crud.phtml", 'consumer',
                array( "programs"=>$this->programs,
               "consumer_id"=>$this->consumer->id) );?>

  
                <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
           </div>
        </div>
    </div>

</form>               