
<form action="/isp/goals" method="post" id="isp-gen-sirs" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/medical',
                                                             'id' => $this->consumer->id,
                                                             'next'=>true,
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
    
    <div class="row">
        <div class="span12">
           <div class="well">
                
                   <strong>Serious Incident Report's for<?=$this->consumer->fname?> <?=$this->consumer->lname?> </strong><br />
                   <small>(Please list all SIR's written since last meeting)</small>
                        <?= $this->partial( "/sirs/partials/crud.phtml", 'consumer',
                            array( "sirs"=>$this->sirs,
                                   "consumer_id"=>$this->consumer->id) );?>  
                <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
           </div>
        </div>
    </div>

</form>