
<form action="/isp/finalize" method="post" id="isp-gen-summary" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/goals',
                                                             'id' => $this->consumer->id,
                                                             'next'=>true,
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
    
    <div class="row">
        <div class="span12">
           <div class="well">
                
                <strong>Isp Summary for <?=$this->consumer->fname?> <?=$this->consumer->lname?> </strong>
                <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
           </div>
        </div>
    </div>

</form>