
<form action="/isp/finalize" method="post" id="isp-gen-summary" >

    <?= $this->partial("/isp/partials/progress.phtml", array('percentComplete'=>$this->percentComplete,
                                                             'back'=>'/isp/programs',
                                                             'id' => $this->consumer->id,
                                                             'next'=>true,
                                                             'formName'=>$this->formName,
                                                             'steps'=>$this->steps,
                                                             'activeStep'=>$this->activeStep)); ?>
    
    <div class="row">
        <div class="span12">
           <div class="well">
            
               <p>
               <strong>Isp Summary for <?=$this->consumer->fname?> <?=$this->consumer->lname?> </strong>
               </p>
               
               <label for="isp-summary">Summary:</label>
               <textarea id='isp-summary' name="isp-summary"></textarea><br />

                <label for="total-hours">Total Hours:</label>
                <input type="text" name="total-hours" value="" id="total-hours"/>
                    
                <label for="print-name">Please print name of person who completed this report:</label>
                <input type="text" name="print-name" value="<?=$this->user->fname?> <?=$this->user->lname?>" id="print-name"/>
                
                <label for="isp-date">Date:</label>
                <input type="text" name="isp-date" value="<?=date("m-d-Y")?>" id="isp-date"/>
                
                
                
                <input type="hidden" name="id" value="<?=$this->consumer->id?>" />
           </div>
        </div>
    </div>

</form>