<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <?=$this->headTitle(SITE_NAME) ?>
       
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        
        <?= $this->headMeta();?>
        
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/css/datepicker.css">

        <?= $this->headLink();?>
        
        <script src="/js/vendor/jquery-1.10.1.min.js"></script>
        
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><?=SITE_NAME?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="/">Home</a></li>
                            
                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consumers <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/consumers/assigned">Assigned To Me</a></li>
                                    <li><a href="/consumers">View All</a></li>
                                    <li><a href="/consumer/new">New</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Medical</li>
                                    <li><a href="/physicians">Physicians</a></li>
                                    <li><a href="/pharmaceuticals/">Pharmaceuticals</a></li>
                                    <li><a href="#">Conditions</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="/reports" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/isp">Sample ISP *</a></li>
                                    
                                    <li><a href="#">Other Reports to come.</a></li>
                                    <li><a href="#">Goals</a></li>
                                   <li class="divider"></li>
                                    <li class="nav-header">Report Due Dates</li>
                                    <li><a href="#">View All</a></li>
                                    <li><a href="#"></a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="navbar-form pull-right">
                            <?= $this->GetAuthLink()?>
                        </div>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        
        <div class="container-push"> </div>    
        
        <div class="container navbar-push">

            <?= $this->flashMessages(); ?>
            
            <?php echo $this->layout()->content; ?>
            
            <hr>
            
            <footer>
                <p>&copy; <?=SITE_NAME?> <?=date("Y")?></p>
            </footer>
            
        </div>
        <!-- /container -->


        <div id="mainModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="mainModalLabel">Modal header</h3>
            </div>

            <div id="mainModalBody" class="modal-body"> </div>
            <div id="mainModalFooter" class="modal-footer"> </div>
        </div>
        
        
        <div class="modal hide fade" id="confirm-dialog">
            
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h3>Confirm</h3>
            </div>
            
            <div class="modal-body" style="min-height:50px;"> </div>
            
            <div class="modal-footer">
                <a class="btn btn-danger">Ok</a>
                <a class="btn btn-cancel" data-dismiss="modal">Cancel</a>
            </div>
            
        </div>
        

        <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <script src="/js/vendor/bootstrap.min.js"></script>
        <script src="/js/vendor/underscore.js"></script>
        <script src="/js/vendor/bootstrap-datepicker.js"></script>
        <script src="/js/main.js"></script>
        <?=$this->headScript();?>
        
        <script id="date-template" type="text/plain">
            <div data-date-format="dd-mm-yyyy" data-date="<%= start %>" id="<%= id %>" class="input-append date">
            <%= field %>
            <span class="add-on"><i class="icon-calendar"></i></span>
            </div>
        </script>

    </body>
</html>
