<!DOCTYPE html>
<html>
  <head>
    
    <?= $this->headTitle();?>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />
    
    <link rel="stylesheet" href="/css/main.css"> 
    <?= $this->headMeta();?>        
    
    <script src="/js/vendor/jquery-1.10.1.min.js"></script>
       
  </head>
  <body>
 
    <?php echo $this->layout()->content; ?>
    
    <script src="/js/main.js"></script>
    <?=$this->headScript();?>
  
  </body>
</html>