<? if( $this->layout ):?>
    <?$this->headScript()->appendFile('/js/views/tools/crud/index.js')?>
    <h2><?=$this->escape($this->displayName)?></h2>
    <?= $this->partial('/partials/button.phtml','default',
                       array('link'=>$this->escape($this->createUrl)."/page/".$this->escape($this->page),
                       'label'=>'Add New')) ?>
<hr />
<?endif;?>

  <? $header = $this->crud->visible;
   array_walk($header, function(&$n) {
      $n = ucwords( str_replace("_", " ", $n));
   });
  
     $header[] = "edit";
     $header[] = "delete"; ?>
     
 <?= $this->TableHead( $header , "table table-striped crud-index", "crud-index" ) ?>
    
    <? if(isset( $this->results)): ?>                 
    <?foreach($this->results as $r):?>  
        <? $rows = array();
            foreach( $this->crud->visible as $vis ) {
                $rows[] = $this->escape(  strlen($r->$vis) > 50 ? $this->truncate($r->$vis) : $r->$vis   );   
            }
           $rows[] = "<a id='crud-edit-".(int)$r->id."' href='".$this->escape($this->updateUrl)."/id/".(int)$r->id."/page/".(int)$this->page."' class='pointer curd-edit' data-id='".(int)$r->id."' title='edit'><i class='icon-edit'></i></a>";
           $rows[] = "<a id='crud-edit-".(int)$r->id."' class='pointer curd-del' data-url='".$this->escape($this->deleteUrl)."' data-id='".(int)$r->id."' title='delete'><i class='icon-remove'></i></a>";
        ?>
        <?= $this->TableRow($rows, "id='crud-item-".(int)$r->id."'"); ?>
    <?endforeach;?>    
<?endif;?>

<?= $this->TableFoot() ?>

<? if( $this->layout ):?>
<hr />
<?endif;?>


<? if( $this->paging  ):?>
    <?= $this->paginate ?>
<?endif;?>


<? if( $this->layout ):?>
    <script src="<?=$this->escape($this->templateUrl)?>" id="curd-js-template" type="text/plain"></script>
<?endif;?>
