<h2>Exams</h2>
<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/exam/new/cid/'.$this->consumer_id, 'label'=>'Add New')) ?>
<hr />
<? if(isset( $this->physicians )): ?>
    <?= $this->TableHead( array("Physician Name",
                                "Address",
                                "Telephone #",
                                "Type of Exam",
                                "Date of Last Exam",
                                "Result of Exam",
                                "Delete" ), "table table-striped table-bordered" ) ?>
  
    <?foreach($this->physicians as $p):?>
    <?foreach($p['exams'] as $e):
              $strDate = strtotime( $e->date );?>
 
        <?= $this->TableRow(array( "<a href='/consumer/exam/edit/cid/{$this->consumer_id}/id/{$e->id}'>".$p["name"]."</a>",
                                   $p["address"],
                                   $p["phone"],
                                   $e->type,
                                   date('m/d/Y', $strDate ),
                                   $e->result,
                                   "<a href='/consumer/exam/delete/id/{$e->id}/cid/{$this->consumer_id}'><i class='icon-remove'></i></a>")); ?>
    <?endforeach;?>
    <?endforeach;?>
    <?= $this->TableFoot() ?>

<?endif;?>
<hr />
<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/exam/new/cid/'.$this->consumer_id, 'label'=>'Add New')) ?>