<h2>Medicals Appointments</h2>
<? if(isset( $this->appointments )): ?>
    <?= $this->TableHead( array("Hospital",
                                "Date",
                                "Time",
                                "Next visit",
                                "Description",
                                "Delete"), "table table-striped js-appointments-index" ) ?>
  
    <?foreach($this->appointments as $a):?>
    <? $id = $a->id?>
        <?= $this->TableRow(array( "<a href='/appointment/edit/id/".$a->id."'>".$this->escape($a->hospital)."</a>",
                                   $this->escape($a->date),
                                   $this->escape($a->time). " " .$this->escape($a->ampm),
                                   $this->escape($a->next),
                                   $this->escape($a->description),    
                                   "<center><a class='pointer crud-new-update-appointments' data-id='{$id}' data-cid='{$this->consumer_id}'><i class='icon-edit'></i></a></center>",
                                   "<center><a class='crud-del-appointments icon icon-remove' data-id='{$id}'></a></center>")
			          ,"class='appointments-row-{$id} highlight-child'"); ?>
    <?endforeach;?>
    <?= $this->TableFoot("<tr><td colspan='7'><a class='crud-new-update-appointments pull-right'
                                                     data-id=''
                                                     data-cid='{$this->consumer_id}'>Add Goal
                                                     <i class='icon icon-plus'></i></a></td></tr>" ) ?>
<?endif;?>

<script type="text/plain" id="js-crud-edit-appointments">
	<% if( action == 'new' ){%>
	<tr class="appointments-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	<td><%= helpers.escapeHtml(values.hospital) %></td>
	<td><%= helpers.escapeHtml(values.date) %></td>
        <td><%= helpers.escapeHtml(values.time) %> <%= helpers.escapeHtml(values.ampm) %></td>
        <td><%= helpers.escapeHtml(values.next) %></td>
        <td><%= helpers.escapeHtml(values.description) %></td>
        <td>
	    <center>
		<a class='pointer crud-new-update-appointments' data-id='<%= helpers.escapeHtml(id) %>'>
                    <i class='icon-edit'></i>
		</a>
	    </center>
	</td>
	<td><center><a class="crud-del-appointments icon icon-remove" data-id='<%= helpers.escapeHtml(id) %>'></a></center></td>
	<% if( action == 'new' ){ %>
	</tr>
	<% } %>
</script>