
    <div class="crud-create-update crud-load-template hidden"
                id="appointment-bind-crud"
                data-id=''
                data-path='.:appointment'
                data-form='consumermedappontmentform'
                data-title="Edit Goal Data"
                data-params=''
                data-action='create'
                data-target='js-appointments-index'
                data-template='js-crud-edit-appointments'
                data-callback='lightBox.dateFields'></div>

    <?= $this->TableHead( array("Hospital",
                                "Date",
                                "Time",
                                "",
                                ""), "table table-striped small-txt js-appointments-index", "js-appointments-index" ) ?>
                                
<? if(isset( $this->appointments )): ?>

    <?foreach($this->appointments as $a):?>
    <? $id = $a['id']?>
    <?= $this->TableRow(array("<a data-id='".$id."' class='crud-view-appointment'>".$this->escape(strlen( $a['hospital']) > 30 ? $this->Truncate($a['hospital'],30) : $a['hospital'])."</a>",
                              $this->escape($a['date']),
                              $this->escape($a['time']). " " .$this->escape($a['ampm']),
                              "<center><a class='crud-create-update'
                                                 data-params='id:{$id},cid:{$this->consumer_id}'
                                                 data-action='update'
                                                 data-bind='appointment-bind-crud'><i class='icon-edit'></i></a></center>",
                              "<center><a class='crud-delete icon icon-remove'
                                                data-params='id:{$id}'
                                                data-bind='appointment-bind-crud'></a></center>"),
                             "class='crud-row-{$id} highlight-child'"); ?>
    <?endforeach;?>

<?endif;?>

<?= $this->TableFoot("<tr><td colspan='5'><a class='crud-create-update pull-right'
                                                 data-action='create'
                                                 data-bind='appointment-bind-crud'
                                                 data-params='consumer_id:{$this->consumer_id}'>Add Appointment</a></td></tr>" ) ?>

<script type="text/plain" id="js-crud-edit-appointments">
	<% if( action == 'new' ){%>
	<tr class="crud-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	<td><%= helpers.escapeHtml(values.hospital.substr(0,30)) %></td>
	<td><%= helpers.escapeHtml(values.date) %></td>
        <td><%= helpers.escapeHtml(values.time) %> <%= helpers.escapeHtml(values.ampm) %></td>
        <td>
        <center><a  class='crud-create-update'
                    data-params='id:<%= helpers.escapeHtml(id) %>,cid:<%= helpers.escapeHtml(values.consumer_id) %>'
                    data-action='update'
                    data-bind='appointment-bind-crud'><i class='icon-edit'></i></a>
        </center>
        </td>
        
        <td>
        <center><a class='crud-delete icon icon-remove'
                   data-params='id:<%= helpers.escapeHtml(id) %>'
                   data-bind='appointment-bind-crud'></a></center>
        </td>        
        
        <% if( action == 'new' ){ %>
	</tr>
	<% } %>
</script>

<script>
    
    $("body").delegate(".crud-view-appointment", "click", function(){
        
        var id = $(this).attr('data-id');
     
        lightBox.show('mainModal', 'Appointment Info',
                                {'remote':'/appointment/read/id/'+id+'/',
                                 'params': { id:id},
                                 'callback':function(data) {
                              }},
                              'get');
    
});
</script>