<? if(isset( $this->appointments )): ?>

    <?= $this->TableHead( array("Hospital",
                                "Date",
                                "Time",
                                "",
                                ""), "table table-striped small-txt js-appointments-index" ) ?>
  
    <?foreach($this->appointments as $a):?>
    <? $id = $a['id']?>
    <?= $this->TableRow(array("<a data-id='".$id."' class='crud-view-appointment'>".$this->escape(strlen( $a['hospital']) > 30 ? $this->Truncate($a['hospital'],30) : $a['hospital'])."</a>",
                              $this->escape($a['date']),
                              $this->escape($a['time']). " " .$this->escape($a['ampm']),
                              "<center><a class='crud-new-update-appointments' data-id='{$id}' data-cid='{$this->consumer_id}'><i class='icon-edit'></i></a></center>",
                             "<center><a class='crud-del-appointments icon icon-remove' data-id='{$id}'></a></center>"),
                             "class='appointments-row-{$id} highlight-child'"); ?>
    <?endforeach;?>
    <?= $this->TableFoot("<tr><td colspan='5'><a class='crud-new-update-appointments pull-right'
                                                     data-id=''
                                                     data-cid='{$this->consumer_id}'>Add Appointment            
                                                     <i class='icon icon-plus'></i></a></td></tr>" ) ?>
<?endif;?>

<script type="text/plain" id="js-crud-edit-appointments">
	<% if( action == 'new' ){%>
	<tr class="appointments-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	<td><%= helpers.escapeHtml(values.hospital.substr(0,30)) %></td>
	<td><%= helpers.escapeHtml(values.date) %></td>
        <td><%= helpers.escapeHtml(values.time) %> <%= helpers.escapeHtml(values.ampm) %></td>
        <td>
	    <center>
		<a class='pointer crud-new-update-appointments' data-id='<%= helpers.escapeHtml(id) %>'>
                    <i class='icon-edit'></i>
		</a>
	    </center>
	</td>
	<td><center><a class="crud-del-appointments icon icon-remove" data-id='<%= helpers.escapeHtml(id) %>'></a></center></td>
	<% if( action == 'new' ){ %>
	</tr>
	<% } %>
</script>