<div class="crud-create-update crud-load-template hidden"
            id="status-bind-crud"
            data-id=''
            data-path='/medical/status'
            data-form='consumersmedicalstatus'
            data-title="Edit Health Status"
            data-params='',
            data-action='create'
            data-target='js-status-index'
            data-template='js-crud-edit-status'
            data-callback='lightBox.dateFields'
            data-template-path='consumers/medical/status'></div>

<h4><?= (isset($this->title)) ? $this->title : "Health Status" ; ?></h4>

 <?= $this->TableHead( array("Date",
                             "Weight",
                             "Height",
                             "Blood Pressure",
                             "Cholesterol",
                                "",
                                ""), "table table-striped small-txt js-status-index", "js-status-index" ) ?>
                                
<? if(isset( $this->medicalStatus )): ?>

    <?foreach($this->medicalStatus as $ms):?>
    <? $id = $ms['id']?>
    <?= $this->TableRow(array("<a data-id='".$id."' class='crud-view-med-status'>".$this->escape($ms['date'])."</a>",
                              $this->escape($ms['weight']),
                              $this->escape($ms['height']),
                              $this->escape($ms['blood_pressure']),
                              $this->escape($ms['cholesterol']),
                              "<center><a class='crud-create-update'
                                                 data-params='id:{$id},cid:{$this->consumer_id}'
                                                 data-action='update'
                                                 data-bind='status-bind-crud'><i class='icon-edit'></i></a></center>",
                              "<center><a class='crud-delete icon icon-remove'
                                                data-params='id:{$id}'
                                                data-bind='status-bind-crud'></a></center>"),
                             "class='crud-row-{$id} highlight-child'"); ?>
    <?endforeach;?>

<?endif;?>

<?= $this->TableFoot("<tr><td colspan='7'><a class='crud-create-update pull-right'
                                                 data-action='create'
                                                 data-bind='status-bind-crud'
                                                 data-params='consumer_id:{$this->consumer_id}'>New Health Report</a></td></tr>" ) ?>

<script type="text/plain" id="js-crud-edit-status">
    <% if( action == '_create' ){%>
    <tr class="crud-row-<%= helpers.escapeHtml(id) %> highlight-child">
    <%}%>
    <td><a data-id='<%= helpers.escapeHtml(id) %>' class='crud-view-appointment'><%= helpers.escapeHtml(values.date) %></a></td>
    <td><%= helpers.escapeHtml(values.weight) %></td>
    <td><%= helpers.escapeHtml(values.height)%></td>
    <td><%= helpers.escapeHtml(values.blood_pressure)%></td>
    <td><%= helpers.escapeHtml(values.cholesterol)%></td>
    
    <td>
    <center><a class='crud-create-update'
              data-params='id:<%= id %>,cid:<%= values.consumer_id %>'
              data-action='update'
              data-bind='status-bind-crud'><i class='icon-edit'></i></a></center>
    </td>
    
    <td>
    <center><a class='crud-delete icon icon-remove'
                      data-params='id:<%= id %>'
                      data-bind='status-bind-crud'></a></center>
    </td>
    <% if( action == '_create' ){ %>
    </tr>
    <% } %>
</script>
