<h4>Please double check insurance information.</h4>

<?= $this->TableHead( array("Insurance Type",
                            "Medical #",
                            "Medicare #",
                            "Information",
                            "Edit",
                            "Delete" ), "table table-bordered js-insurance-index" ) ?>
   
<?if(isset($this->insurance)):?>
   <?foreach($this->insurance as $k=>$i):?>

    <?= $this->TableRow(array( $this->escape($i['type']),
                           $this->escape($i['medical_number']),
                           $this->escape($i['medicare_number']),
                                                           $this->escape($i['insurance_info']),
                           "<center><a class='pointer crud-new-update-insurance' data-id='{$i['id']}'><i class='icon-edit'></i></a></center>",
                                                           "<center><a class='crud-del-insurance icon icon-remove' data-id='{$i['id']}'></a></center>"
                                                           ), "class='insurance-row-{$i['id']} highlight-child'"); ?>
   
   <?endforeach;?>
<?endif;?>
   
<?= $this->TableFoot("<tr><td colspan='6'><a class='crud-new-update-insurance pull-right'
                                                 data-id=''
                                                     data-cid='{$this->consumer_id}'>Add Insurance
                                                     <i class='icon icon-plus'></i></a></td></tr>" ) ?>


<script type="text/plain" id="js-crud-edit-insurance">
	<% if( action == 'new' ){%>
	<tr class="insurance-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	<td><%= helpers.escapeHtml(values.type) %></td>
	<td><%= helpers.escapeHtml(values.medical_number) %></td>
	<td><%= helpers.escapeHtml(values.medicare_number) %></td>
	<td><%= helpers.escapeHtml(values.insurance_info) %></td>
	<td>
		<center>
			<a class='pointer crud-new-update-insurance' data-id='<%= helpers.escapeHtml(id) %>'>
				<i class='icon-edit'></i>
			</a>
		</center>
	</td>
	<td><center><a class="crud-del-insurance icon icon-remove" data-id='<%= helpers.escapeHtml(id) %>'></a></center></td>
	<% if( action == 'new' ){ %>
	</tr>
	<% } %>
</script>
		