<?
if( $this->layout ){
$this->headScript()->appendFile('/js/views/consumer/allergies/index.js');
}
?>

<h2>Allergies Insurance Info</h2>

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumers/allergies/new/', 'label'=>'Add New')) ?>
<hr />

<? if(isset( $this->allergies )): ?>
 <?= $this->TableHead( array("Allergy",
                                "Info",
                                "Delete"), "table table-striped" ) ?>
  
    <?foreach($this->allergies as $a):?>
        <?= $this->TableRow(array( "<a href='/consumers/allergies/edit/id/".$a->id."'>".$a->allergy."</a>",
                                   $a->info,
                                   "<a id='allergy-".$a->id."'
                                   class='pointer del-allergy' data-id='".$a->id."' title='delete'><i class='icon-remove'></i></a>")); ?>
    <?endforeach;?>
    
    <?= $this->TableFoot() ?>
<?endif;?>

<hr />

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumers/allergies/new/', 'label'=>'Add New')) ?>
