<h2>Notes</h2>
<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/notes/create/cid/'.$this->consumer_id, 'label'=>'Add New')) ?>
<hr />

<? if(isset( $this->notes )): ?>

    <?= $this->TableHead( array(" ",
                                "Note",
                                "Created",
                                " ",
                                " " ), "table table-striped" ) ?>
  
    <?foreach($this->notes as $n):?>
 
        <?= $this->TableRow(array( "<img src=\"/image/db/".$this->consumer_id."/c\" class='thumb'/>", 
                                   $this->truncate($n["note"], 150),
                                   date('m/d/Y', strtotime($n["created"]) ),
                                   "<a href='/consumer/notes/update/cid/".$this->consumer_id."/id/".$n["id"]."' title='edit'><i class='icon-edit'></i></a>",
                                   "<a href='/consumer/notes/delete/cid/".$this->consumer_id."/id/".$n["id"]."' title='delete'><i class='icon-remove'></i></a>")); ?>
    <?endforeach;?>
    <?= $this->TableFoot() ?>

<?endif;?>


