<?php
$prevYear  = $this->year;
$nextYear  = $this->year;
$prevMonth = (int)$this->month - 1;
$nextMonth = (int)$this->month + 1;
$currMonth = $this->month;
 
if ($prevMonth == 0 ) {
    $prevMonth = 12;
    $prevYear = $this->year - 1;
}

if ($nextMonth == 13 ) {
    $nextMonth = 1;
    $nextYear = $this->year + 1;
}

if($nextMonth < 10) {
    $nextMonth  = '0'.(int)$nextMonth;
}

if($prevMonth < 10) {
    $prevMonth  = '0'.(int)$prevMonth;
}

if($currMonth < 10) {
    $currMonth  = '0'.(int)$currMonth;
}

    

?>
<table id="js-calendar"
       width="100%"
       data-date="<?=$this->year.'-'.$currMonth.'-'.$this->day?>" 
       data-year="<?=$this->year?>" 
       data-month="<?=$currMonth?>" 
       data-day="<?=$this->day?>"       
       class="table table-striped table-bordered">
    <thead>    
    <tr>
        <th colspan="7" ><h4 id="js-calendar-monthName" class="text-center">
            <?= Base_Functions_Date::MonthNames($this->month-1).' '.$this->year; ?></h4>
            <a class="pull-left pointer js-calendar-nextprev" data-year="<?=$prevYear?>" data-month="<?=$prevMonth?>">Previous</a>
            <a class="pull-right pointer js-calendar-nextprev" data-year="<?=$nextYear?>" data-month="<?=$nextMonth?>">Next</a>
        </th>
    </tr>
    <tr>
        <th><strong>S</strong></th>
        <th><strong>M</strong></th>
        <th><strong>T</strong></th>
        <th><strong>W</strong></th>
        <th><strong>T</strong></th>
        <th><strong>F</strong></th>
        <th><strong>S</strong></th>
    </tr>
    </thead>

    <tbody>
     <?=$this->CalendarDays($this->month,
                            $this->year,
                            $this->day,
                            $this->customClass)?>
    </tbody>    
</table>