<div class="accordion" id="accordion2">
    <div class="accordion-group">
    <div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
    My Time Sheet
    </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse in">
    <div class="accordion-inner">
    time sheet here
    </div>
    </div>
    </div>
    <div class="accordion-group">
    <div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
    My Inbox
    </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
    <div class="accordion-inner">
    inbox message here
    </div>
    </div>
    </div>
</div>