

<p>
<a href="/consumer/new" class="btn btn-small btn-primary"> Add New </a>
</p>


<table class="table table-bordered table-hover table-striped ">
<tbody>

<? if(isset($this->consumers)): ?>
    
    
    
    <thead>
        <tr>
            <th>Type</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            
        </tr>
    </thead>

    <?foreach( $this->consumers as $consumer ):?>
            <tr class="js-display-edit-icon" consumer:id="<?=$consumer->id?>">
            <td><?=$consumer->type?></td>
            <td><a href="/consumer/view/<?=$consumer->id?>"><?=$consumer->fname?> <?=$consumer->lname?></a></td>
            <td><?=$consumer->phone?></td>
            <td>
                <?=$consumer->email?> 
                <div class="js-edit-icon pull-right pointer width40px height10px" > </div>
            </td>
            
            </tr>
    <?endforeach;?>


<? endif; ?>

</tbody>
</table>


<script>
    
   $(function() {
    
          $(".js-display-edit-icon").each( function(){ 
            
            var ele = $(this);
            //onclick
            ele.click( 
                function() { 
                     window.location = "/consumer/edit/"+ele.attr('consumer:id');
                });
            //onmouse over    
            ele.mouseenter(
                function () {
                     ele.find("div:last").append($("<p class='pull-right'><i class='icon-edit'> </i> <small>edit</small></p>"));
                });
             //on mouse out
             ele.mouseleave( 
                function () {
                     ele.find("p:last").remove();
                }
            );
            
       });
    
    
    });


</script>
