

<p>
<a href="/consumer/new" class="btn btn-small btn-primary"> Add New </a>
</p>


<table class="table table-bordered table-hover table-striped ">
<tbody>

<?php 

 print Base_Functions_Math::distanceBetweenCoords(38.730013, -120.8050906, 40.714623,-74.006605, "M");

?>


<? if(isset($this->consumers)): ?>
    <thead>
        <tr>
            <th>Type</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <?if(isset($this->checkin) && $this->checkin == true):?>
            <th>Check-In</th>
            <?endif;?>
        </tr>
    </thead>

    <?foreach( $this->consumers as $consumer ):?>
            <tr>
            <td><?=$consumer->type?></td>
            <td><a href="/consumer/view/<?=$consumer->id?>"><?=$consumer->fname?> <?=$consumer->lname?></a></td>
            <td><?=$consumer->phone?></td>
            <td>
                <?=$consumer->email?> 
                <div class="js-edit-icon pull-right pointer width40px height10px" > </div>
            </td>
            
            <?if(isset($this->checkin) && $this->checkin == true):?>
            <td>
                <a class="pointer js-check-in btn" consumer:id="<?=$consumer->id?>">
                Check-in <i class="icon-map-marker"></i> </a> 
            </td>
            <?endif;?>
            
            </tr>
    <?endforeach;?>
<? endif; ?>
</tbody>
</table>

<script>
    
   $(function() {
           
       $(".js-check-in").click(function(){
            Check.In($(this).attr('consumer:id'));  
       });
        
    });
    
    
    var Check = { 
                    In:function(consumer_id) {
                        console.log(consumer_id);
                        Check.Geo();
                        
                    },
                    
                    
                    Geo:function() {
                    
                     if(navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(function(position) {
                            console.log(position.coords.latitude);
                            console.log(position.coords.longitude);
                            });
                       
                    }
                }
}
</script>
