<? $this->headScript()->appendFile('/js/views/consumer/view.js'); ?>

<ul class="nav nav-tabs">
    <li class="active"><a href="#consumerinfo" data-toggle="tab">Info</a></li>
    <li><a href="#caseNotes" data-toggle="tab">Case Notes</a></li>
    <li><a href="#medical" data-toggle="tab">Medical</a></li>
</ul>


<div class="tab-content">
<div class="tab-pane active" id="consumerinfo">

<div class='data'>
    <input type="hidden" id="page-data-consumer-id" value="<?=$this->consumer->id?>" />
</div>


<? if (isset($this->consumer)): ?>
<? $this->headTitle($this->consumer->fname ." ".$this->consumer->lname); ?>
        <div class="row-fluid">
            <div class="span4">    
                <div><a class="pointer js-edit-assignee" consumer:id="<?=$this->consumer->id?>" > Assign employee</a>   </div>
                
                <?if ( isset($this->users)): ?>
                    <?= $this->partial('partials/consumer-users.phtml', 'consumer', array('users'=>$this->users)); ?>
                <?endif;?>
               
               
                <div><a class="pointer js-assign-coordinator" consumer:id="<?=$this->consumer->id?>" > Assign Service Coordinator</a>   </div>
                <?if ( isset($this->coordinators)): ?>
                    <?= $this->partial('partials/consumer-coordinators.phtml', 'consumer', array('coordinators'=>$this->coordinators)); ?>
                <?endif;?>               
                  
            </div>
            
            <div class="span8">

            <table class="table">
                <thead>
                    <tr>
                        <th colspan="7">
                            
                            <h3><?= $this->consumer->fname ?> <?= $this->consumer->lname ?></h3>
                            
                            <img src="/image/db/<?=$this->consumer->id?>/c"
                                 consumer:id="<?=$this->consumer->id?>"
                                 consumer:type="c"
                                 id="js-update-img"
                                 class="img-polaroid pull-left pointer js-update-img" >
                                                
                        </th> 
                    </tr>
                </thead>
                <tbody>
                    
                    <tr><td><?= $this->consumer->type?></tr></td>
                    <tr><td><?= $this->consumer->phone ?></tr></td>
                    <tr><td><?= $this->consumer->email ?></tr></td>
                    <tr><td><?= $this->consumer->address ?> <?= $this->consumer->city ?></tr></td>
                    <tr><td><?= $this->consumer->state ?> <?= $this->consumer->zip ?></tr></td>
                    <tr><td><?= $this->consumer->birth_date?></tr></td>
                    <tr><td>Age: <?= $this->BirthYears($this->consumer->birth_date); ?></tr></td>
                    
                <tbody>
            </table>
                
                <p>
                    <?= $this->consumer->bio ?><br />
                </p>
                
                 <p>       
                    <a class="btn btn-small pull-right btn-primary" href="/consumer/edit/<?=$this->consumer->id?>"> Edit Info </a>    
                 </p>   
                    
            </div>
        </div>
        
        
<?endif;?>
    
    
</div>


<div class="tab-pane" id="caseNotes">
    
<div class="row-fluid">
    
    <div class="span4" id="js-calendar-wrapper">
       <?= $this->partial('partials/calendar.phtml', 'tools',
                          array('day'=>date("d"),
                                'year'=>date("Y"),
                                'month'=> date('n'),
                                'customClass'=>'js-notes-day pointer')); ?> 
    </div>
    
    <div class="span8">  
        <?= $this->partial('partials/consumer-notes.phtml',
                           array('consumer'=>$this->consumer, 'user_id'=>$this->user_id));?>
    </div>

</div>

</div>


<div class="tab-pane" id="medical">
    
<div class="row-fluid">
    
    <div class="span4">
        <?= $this->partial('/partials/consumer-nav.phtml',
                    array('consumer' =>$this->consumer));?>
    </div>        
    
    <div class="span8">  
        <?= $this->partial('/partials/consumer-medical.phtml',
                    array( "physicians"=>$this->physicians,
                           "pharmaceuticals"=>$this->pharmaceuticals  ));?>
        
        <div id="js-med-appointments"> </div>
    </div>

</div>

</div>




</div>

<script>

   $(function() {
           
       $(".js-check-in").click(function(){
            Check.In($(this).attr('consumer:id'));  
       });
       
        
    
   }); 
      
 </script>     
      



