<? $this->headScript()->appendFile('/js/views/consumer/index/view.js'); ?>
<? $this->headScript()->appendFile('/js/views/consumer/notes/crud.js'); ?>


<ul class="nav nav-tabs">
    <li class="active"><a href="#consumerinfo" data-toggle="tab">Info</a></li>
    <li><a href="#caseNotes" data-toggle="tab">Case Notes</a></li>
    <li><a href="#medical" data-toggle="tab">Medical</a></li>
    <li><a href="#health" data-toggle="tab">Health</a></li>
    <li><a href="#goals" data-toggle="tab">Goals</a></li>
    <li><a href="#programs" data-toggle="tab">Programs</a></li>
    <li><a href="#reports" data-toggle="tab">Reports</a></li>
</ul>

<div class="tab-content">

<div class="tab-pane active" id="consumerinfo">
    <? if (isset($this->consumer)): ?>
    <? $this->headTitle($this->consumer->fname ." ".$this->consumer->lname); ?>
            <div class="row-fluid">
                
                <div class="span4">
                    <?= $this->partial('partials/consumer-info-tab.phtml',
                            array('consumer'=>$this->consumer,
                                  'users'=>$this->users,
                                  'coordinators'=>$this->coordinators,
                                  'persons'=>$this->persons));?>
                </div>
                
                <div class="span8">
                      <?= $this->partial('partials/consumer-info.phtml',
                               array('consumer'=>$this->consumer));?>         
                </div>
                
            </div>
    <?endif;?>
</div>


<div class="tab-pane" id="caseNotes">    
<div class="row-fluid">
    
    <div class="span4" id="js-calendar-wrapper">
       <?= $this->partial('partials/calendar.phtml', 'tools',
                          array('day'=>date("d"),
                                'year'=>date("Y"),
                                'month'=> date('n'),
                                'customClass'=>'js-notes-day pointer')); ?> 
    </div>
    
    <div class="span8">  
        <?= $this->partial('partials/consumer-notes.phtml',
                           array('consumer'=>$this->consumer, 'user_id'=>$this->user_id));?>
    </div>
    
</div>
</div>


<div class="tab-pane" id="medical">
<div class="row-fluid">
    <div class="span4">
    
    <ul class="rounded-corners module">
        <li class="module-header">Appointments:</li>
         
        <?= $this->partial('/medical/partials/mini-curd.phtml',
                    array( 'appointments'=>$this->appointments, 'consumer_id'=>$this->consumer->id));?>    
        
        <div id="js-med-appointments"> </div>     
    </ul>

    </div>
    
    <div class="span8">  
        <?= $this->partial('/partials/consumer-medical.phtml',
                    array( "physicians"=>$this->physicians,
                           "medications"=>$this->medications,
                           'hospitalized'=>$this->hospitalized,
                           'allergies' => $this->allergies,
                           'insurance'=>$this->insurance,
                           'physiciansExams'=>$this->physiciansExams,
                           'appointments'=>$this->appointments,
                           'consumer_id'=>$this->consumer->id));?>
        
    </div>
</div>
</div>

<div class="tab-pane" id="health">
<div class="row-fluid">
    <div class="span4">
    
    <ul class="rounded-corners module">
        Medical Health Carts will be populated when the Consumer has at least 3 months of data
    </ul>

    </div>
    
    <div class="span8">  
        <?= $this->partial('/medical/partials/status-crud.phtml',
                           array("medicalStatus"=>$this->medicalStatus,
                                 "consumer_id"=>$this->consumer->id));?>
    </div>
</div>
</div>


<div class="tab-pane" id="goals">
<div class="row-fluid">
    <div class="span12">

        <?= $this->partial( "/goals/partials/crud.phtml", 'consumer',
                array( "goals"=>$this->goals,
                       "consumer_id"=>$this->consumer->id) );?>    
    </div>
</div>
</div>

<div class="tab-pane" id="programs">
<div class="row-fluid">
    <div class="span12">
        <?= $this->partial( "/program/partials/crud.phtml", 'consumer',
                array( "programs"=>$this->programs,
                       "consumer_id"=>$this->consumer->id) );?>   
     
    </div>
</div>
</div>


<div class="tab-pane" id="reports">
<div class="row-fluid">
    <div class="span12">
    Reports
    </div>
</div>
</div>


<!-- end tab wrapper -->
</div>