<h4>If consumer was hospitalized or taken to the Emergency Room</h4>

<?= $this->TableHead( array("Hospital",
                            "Reasion",
                            "Date",
                            "Duration of Stay",
                            "Edit",
                            "Delete" ), "table table-bordered js-hospital-index" ) ?>
	   
    <?if(isset($this->hospitalized)):?>
       <?foreach($this->hospitalized as $k=>$h):?>
        <?= $this->TableRow(array( $this->escape($h->hospital),
                                   $this->escape($h->reason),
                                   $this->escape($h->date),
                                   $this->escape($h->duration_of_stay),
                                   "<center><a class='pointer crud-new-update-hospital' data-id='{$h->id}' data-cid='{$h->consumer_id}'><i class='icon-edit'></i></a></center>",
                                   "<center><a class='crud-del-hospital icon icon-remove' data-id='{$h->id}'></a></center>"
                                   ), "class='hospital-row-{$h->id} highlight-child'"); ?>
       
       <?endforeach;?>
   <?endif;?>
	   
    <?= $this->TableFoot("<tr><td colspan='6'><a class='crud-new-update-hospital pull-right'
                                                     data-id=''
                                                     data-cid='{$this->consumer_id}'>Add Hospital Visit
                                                     <i class='icon icon-plus'></i></a></td></tr>" ) ?>

<script type="text/plain" id="js-crud-edit-hospital">
	<% if( action == 'new' ){%>
            <tr class="hospital-row-<%= helpers.escapeHtml(id) %> highlight-child">
	<%}%>
	
        <td><%= helpers.escapeHtml(values.hospital) %></td>
	<td><%= helpers.escapeHtml(values.reason) %></td>
        <td><%= helpers.escapeHtml(values.date) %></td>
	<td><%= helpers.escapeHtml(values.duration_of_stay) %></td>
        <td>
	    <center>
		<a class='pointer crud-new-update-hospital' data-id='<%= helpers.escapeHtml(id) %>'>
                    <i class='icon-edit'></i>
		</a>
	    </center>
	</td>
	<td>
            <center>
                <a class="crud-del-hospital icon icon-remove" data-id='<%= helpers.escapeHtml(id) %>'></a>
            </center>
        </td>
	
        <% if( action == 'new' ){ %>
            </tr>
	<% } %>
</script>