<h4>Current Health Status</h4>
	
<table class="table table-bordered">
    <tbody>
        <tr>
            <td>
                <label for="current_health_status">
                    Hospital/Surgeries/E.R. visits<br />
                    <small>(Name of hospital, reason & dates of stay) : N/A</small>
                </label>    
            </td>    
            <td colspan="3">
                <textarea cols="8" rows="4" id="current_health_status" name="current_health_status" class="textarea-standard-size"></textarea>
            </td>
        </tr>
        <tr>            
            <td>
               <label for="next_appointment">
                Next Doctors Appointment<br><small>(date & time):</small>
                </label>
            </td>
            <td>
                <input type="text" id="next_appointment" name="next_appointment" />
            </td>
            <td>
                <label for="next_appointment_contact">
                Address and Phone:
                </label>
            </td>
            <td>
                <input type="text" id="next_appointment_contact" name="next_appointment_contact" />
            </td>
        </tr>
        <tr>
            <td>
                <label for="next_appointment_info">
                    Appointment Information<br />
                    <small>(attach medical notes if necessary):</small>
                </label>    
            </td>
            <td colspan="3">
                <textarea id="next_appointment_info" name="next_appointment_info" class="textarea-standard-size"></textarea>
            </td>
        </tr>
    </tbody>
</table>



<h4>(Medical Information will be updated when consumer is established with ILS Instructor)</h4>
