


<div class="navbar">
    <div class="navbar-inner pos-rel">
        
        <span class="brand">
            <?=$this->formName?>        
        </span>
        
        <ul class="nav">   
             
            <?foreach( $this->steps as $key=>$step ):?>
                <li class="<?=($this->activeStep == $key) ? 'active' : ''?>">
                    <a href="/isp/<?=strtolower( $step == 'Start' ? 'index' : $step )?>/id/<?=$this->id?>"><?=$step?></a>
                </li>
            <?endforeach;?>
        </ul>       

        <div class="pos-abs" style="right:10px; top:0px;">
            
            <div class="row no-pad no-margin">
                
            <div class="span3 no-pad no-margin">
                <div class="progress" style="margin:10px 0px 0px 0px; width:250px;">
                    <? if($this->activeStep == 'start'):?>
                    <? $this->percentComplete = 0; ?>
                    <?endif;?>
                    <div class="bar" style="width: <?=$this->percentComplete?>%;">
                        <?=round($this->percentComplete,0)?>%
                    </div>
                </div>
            </div>
            
            <?if(!empty($this->next)):?>
                <div class="span2 no-pad no-margin" >
                        <input type="submit" class="btn btn-success pull-right" value="Next &gt;&gt;">
                </div>   
            <?endif;?>
            
            <?if(isset($this->customNext) && !empty($this->customNext)):?>
                <?=$this->customNext?>
            <?endif;?>
                    
            </div>
        </div>


    </div>
</div>

