<a class="btn btn-primary btn-large" href="/{model}"> Back To List </a> <br />
<? if(isset( $this->{model}) ):?>
<table class="table table-striped">  

    <thead>
        <tr>
            <th>Id</th>
        </tr>
        
    </thead>
 
    <tbody id="{model}-data">
    <tr>
        <td>
            <a href="/{model}/update/id/<?=$this->{model}['id']?>" title="Edit"><i class="icon-edit"></i></a>
        </td>
    </tr>
    
    </tbody>
</table>
<? endif;?>

<? var_dump( $this->{model} );?>
