<?
if( $this->layout ){
$this->headScript()->appendFile('/js/views/consumer/hospitalized/index.js');
}
?>

<h2>Allergies Insurance Info</h2>

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/hospitalized/new/cid/'.$this->consumer_id, 'label'=>'Add New')) ?>
<hr />

<? if(isset( $this->hospitalized )): ?>
 <?= $this->TableHead( array("Hospital",
                             "Reason",
                             "Date",
                             "Duration",z
                             "Delete"), "table table-striped" ) ?>
  
    <?foreach($this->hospitalized as $h):?>
    <?$date = strtotime( $h->date );?>
    <?$h->date = date( 'm-d-Y', $date );?>
    
        <?= $this->TableRow(array( "<a href='/consumer/hospitalized/edit/id/".$h->id."'>".$this->escape($h->hospital)."</a>",
                                   $this->escape($h->reason),
                                   $this->escape($h->date),
                                   $this->escape($h->duration_of_stay),
                                   "<a id='hospitalized-".$h->id."'
                                   class='pointer del-hospitalized' data-id='".$h->id."' title='delete'><i class='icon-remove'></i></a>")); ?>
    <?endforeach;?>
    
    <?= $this->TableFoot() ?>
<?endif;?>

<hr />

<?= $this->partial('/partials/button.phtml',
                   'default',
                   array('link'=>'/consumer/hospitalized/new/cid/'.$this->consumer_id, 'label'=>'Add New')) ?>
